// GrandiSotterranei
var traduzioniGrandiSotterranei = {
    "purpursphäre s": "Bilia rossa S",
    "indigosphäre s": "Bilia blu S",
    "jadesphäre s": "Bilia verde S",
    "prismensphäre s": "Bilia prisma S",
    "weißsphäre s": "Bilia tersa S",
    "purpursphäre l": "Bilia rossa L",
    "indigosphäre l": "Bilia blu L",
    "jadesphäre l": "Bilia verde L",
    "prismensphäre l": "Bilia prisma L",
    "weißsphäre l": "Bilia tersa L",
    "beleber": "Revitalizzante",
    "top-beleber": "Revitalizz. Max",
    "purpurstück": "Coccio Rosso",
    "indigostück": "Coccio Blu",
    "gelbstück": "Coccio Giallo",
    "grünstück": "Coccio Verde",
    "sonnenstein": "Pietrasolare",
    "mondstein": "Pietralunare",
    "feuerstein": "Pietrafocaia",
    "donnerstein": "Pietratuono",
    "wasserstein": "Pietraidrica",
    "blattstein": "Pietrafoglia",
    "ovaler stein": "Pietraovale",
    "ewigstein": "Pietrastante",
    "spiritkern": "Roccianima",
    "sternenstück": "Pezzo Stella",
    "herzschuppe": "Squama Cuore",
    "wurzelfossil": "Radifossile",
    "klauenfossil": "Fossilunghia",
    "helixfossil": "Helixfossile",
    "domfossil": "Domofossile",
    "altbernstein": "Ambra antica",
    "panzerfossil": "Fossilscudo",
    "kopffossil": "Fossilcranio",
    "steinknochen": "Osso Raro",
    "lichtlehm": "Creta Luce",
    "eisenkugel": "Ferropalla",
    "eisbrocken": "Rocciafredda",
    "glattbrocken": "Roccialiscia",
    "heißbrocken": "Rocciacalda",
    "nassbrocken": "Rocciaumida",
    "enigmafragment s": "Frammento insolito S",
    "enigmafragment l": "Frammento insolito L",
    "granitstein": "Pietradura",
    "feuertafel": "Lastrarogo",
    "wassertafel": "Lastraidro",
    "blitztafel": "Lastrasaetta",
    "wiesentafel": "Lastraprato",
    "frosttafel": "Lastragelo",
    "fausttafel": "Lastrapugno",
    "gifttafel": "Lastrafiele",
    "erdtafel": "Lastrageo",
    "wolkentafel": "Lastracielo",
    "hirntafel": "Lastramente",
    "käfertafel": "Lastrabaco",
    "steintafel": "Lastrapietra",
    "spuktafel": "Lastratetra",
    "dracotafel": "Lastradrakon",
    "furchttafel": "Lastratimore",
    "eisentafel": "Lastraferro",
    "feentafel": "Lastraspiritello",
    "red sphere s": "Bilia rossa S",
    "blue sphere s": "Bilia blu S",
    "green sphere s": "Bilia verde S",
    "prism sphere s": "Bilia prisma S",
    "pale sphere s": "Bilia tersa S",
    "red sphere l": "Bilia rossa L",
    "blue sphere l": "Bilia blu L",
    "green sphere l": "Bilia verde L",
    "prism sphere l": "Bilia prisma L",
    "pale sphere l": "Bilia tersa L",
    "revive": "Revitalizzante",
    "max revive": "Revitalizz. Max",
    "red shard": "Coccio Rosso",
    "blue shard": "Coccio Blu",
    "yellow shard": "Coccio Giallo",
    "green shard": "Coccio Verde",
    "sun stone": "Pietrasolare",
    "moon stone": "Pietralunare",
    "fire stone": "Pietrafocaia",
    "thunder stone": "Pietratuono",
    "water stone": "Pietraidrica",
    "leaf stone": "Pietrafoglia",
    "oval stone": "Pietraovale",
    "everstone": "Pietrastante",
    "odd keystone": "Roccianima",
    "star piece": "Pezzo Stella",
    "heart scale": "Squama Cuore",
    "root fossil": "Radifossile",
    "claw fossil": "Fossilunghia",
    "helix fossil": "Helixfossile",
    "dome fossil": "Domofossile",
    "old amber": "Ambra antica",
    "armor fossil": "Fossilscudo",
    "skull fossil": "Fossilcranio",
    "rare bone": "Osso Raro",
    "light clay": "Creta Luce",
    "iron ball": "Ferropalla",
    "icy rock": "Rocciafredda",
    "smooth rock": "Roccialiscia",
    "heat rock": "Rocciacalda",
    "damp rock": "Rocciaumida",
    "mysterious shard s": "Frammento insolito S",
    "mysterious shard l": "Frammento insolito L",
    "hard stone": "Pietradura",
    "flame plate": "Lastrarogo",
    "splash plate": "Lastraidro",
    "zap plate": "Lastrasaetta",
    "meadow plate": "Lastraprato",
    "icicle plate": "Lastragelo",
    "fist plate": "Lastrapugno",
    "toxic plate": "Lastrafiele",
    "earth plate": "Lastrageo",
    "sky plate": "Lastracielo",
    "mind plate": "Lastramente",
    "insect plate": "Lastrabaco",
    "stone plate": "Lastrapietra",
    "spooky plate": "Lastratetra",
    "draco plate": "Lastradrakon",
    "dread plate": "Lastratimore",
    "iron plate": "Lastraferro",
    "pixie plate": "Lastraspiritello",
    "gema roja s": "Bilia rossa S",
    "gema azul s": "Bilia blu S",
    "gema verde s": "Bilia verde S",
    "gema prisma s": "Bilia prisma S",
    "gema blanca s": "Bilia tersa S",
    "gema roja l": "Bilia rossa L",
    "gema azul l": "Bilia blu L",
    "gema verde l": "Bilia verde L",
    "gema prisma l": "Bilia prisma L",
    "gema blanca l": "Bilia tersa L",
    "revivir": "Revitalizzante",
    "revivir máximo": "Revitalizz. Max",
    "parte roja": "Coccio Rosso",
    "parte azul": "Coccio Blu",
    "parte amarilla": "Coccio Giallo",
    "parte verde": "Coccio Verde",
    "piedra solar": "Pietrasolare",
    "piedra lunar": "Pietralunare",
    "piedra fuego": "Pietrafocaia",
    "piedra trueno": "Pietratuono",
    "piedra agua": "Pietraidrica",
    "piedra hoja": "Pietrafoglia",
    "piedra oval": "Pietraovale",
    "piedra eterna": "Pietrastante",
    "piedra espíritu": "Roccianima",
    "trozo estrella": "Pezzo Stella",
    "escama corazón": "Squama Cuore",
    "fósil raíz": "Radifossile",
    "fósil garra": "Fossilunghia",
    "fósil hélix": "Helixfossile",
    "fósil domo": "Domofossile",
    "ámbar viejo": "Ambra antica",
    "fósil coraza": "Fossilscudo",
    "fósil cráneo": "Fossilcranio",
    "hueso raro": "Osso Raro",
    "refleluz": "Creta Luce",
    "bola férrea": "Ferropalla",
    "roca helada": "Rocciafredda",
    "roca suave": "Roccialiscia",
    "roca calor": "Rocciacalda",
    "roca lluvia": "Rocciaumida",
    "esquirla extraña s": "Frammento insolito S",
    "esquirla extraña l": "Frammento insolito L",
    "piedra dura": "Pietradura",
    "tabla llama": "Lastrarogo",
    "tabla linfa": "Lastraidro",
    "tabla trueno": "Lastrasaetta",
    "tabla pradal": "Lastraprato",
    "tabla helada": "Lastragelo",
    "tabla fuerte": "Lastrapugno",
    "tabla tóxica": "Lastrafiele",
    "tabla terrax": "Lastrageo",
    "tabla cielo": "Lastracielo",
    "tabla mental": "Lastramente",
    "tabla bicho": "Lastrabaco",
    "tabla pétrea": "Lastrapietra",
    "tabla terror": "Lastratetra",
    "tabla draco": "Lastradrakon",
    "tabla oscura": "Lastratimore",
    "tabla acero": "Lastraferro",
    "tabla duende": "Lastraspiritello",
    "sphère rouge s": "Bilia rossa S",
    "sphère bleue s": "Bilia blu S",
    "sphère verte s": "Bilia verde S",
    "sphère prisme s": "Bilia prisma S",
    "sphère pâle s": "Bilia tersa S",
    "sphère rouge l": "Bilia rossa L",
    "sphère bleue l": "Bilia blu L",
    "sphère verte l": "Bilia verde L",
    "sphère prisme l": "Bilia prisma L",
    "sphère pâle l": "Bilia tersa L",
    "rappel": "Revitalizzante",
    "rappel max": "Revitalizz. Max",
    "tesson rouge": "Coccio Rosso",
    "tesson bleu": "Coccio Blu",
    "tesson jaune": "Coccio Giallo",
    "tesson vert": "Coccio Verde",
    "pierre soleil": "Pietrasolare",
    "pierre lune": "Pietralunare",
    "pierre feu": "Pietrafocaia",
    "pierre foudre": "Pietratuono",
    "pierre eau": "Pietraidrica",
    "pierre plante": "Pietrafoglia",
    "pierre ovale": "Pietraovale",
    "pierre stase": "Pietrastante",
    "clé de voûte": "Roccianima",
    "morceau d’étoile": "Pezzo Stella",
    "écaille cœur": "Squama Cuore",
    "fossile racine": "Radifossile",
    "fossile griffe": "Fossilunghia",
    "nautile": "Helixfossile",
    "fossile dôme": "Domofossile",
    "vieil ambre": "Ambra antica",
    "fossile armure": "Fossilscudo",
    "fossile crâne": "Fossilcranio",
    "os rare": "Osso Raro",
    "lumargile": "Creta Luce",
    "balle fer": "Ferropalla",
    "roche glace": "Rocciafredda",
    "roche lisse": "Roccialiscia",
    "roche chaude": "Rocciacalda",
    "roche humide": "Rocciaumida",
    "éclat étrange s": "Frammento insolito S",
    "éclat étrange l": "Frammento insolito L",
    "pierre dure": "Pietradura",
    "plaque flamme": "Lastrarogo",
    "plaque hydro": "Lastraidro",
    "plaque volt": "Lastrasaetta",
    "plaque herbe": "Lastraprato",
    "plaque glace": "Lastragelo",
    "plaque poing": "Lastrapugno",
    "plaque toxicité": "Lastrafiele",
    "plaque terre": "Lastrageo",
    "plaque ciel": "Lastracielo",
    "plaque esprit": "Lastramente",
    "plaque insecte": "Lastrabaco",
    "plaque roc": "Lastrapietra",
    "plaque fantôme": "Lastratetra",
    "plaque draco": "Lastradrakon",
    "plaque ombre": "Lastratimore",
    "plaque fer": "Lastraferro",
    "plaque pixie": "Lastraspiritello",
    "べにタマｓ": "Bilia rossa S",
    "あおタマｓ": "Bilia blu S",
    "みどりタマｓ": "Bilia verde S",
    "こんごうダマｓ": "Bilia prisma S",
    "しらタマｓ": "Bilia tersa S",
    "べにタマｌ": "Bilia rossa L",
    "あおタマｌ": "Bilia blu L",
    "みどりタマｌ": "Bilia verde L",
    "こんごうダマｌ": "Bilia prisma L",
    "しらタマｌ": "Bilia tersa L",
    "げんきのかけら": "Revitalizzante",
    "げんきのかたまり": "Revitalizz. Max",
    "あかいかけら": "Coccio Rosso",
    "あおいかけら": "Coccio Blu",
    "きいろいかけら": "Coccio Giallo",
    "みどりのかけら": "Coccio Verde",
    "たいようのいし": "Pietrasolare",
    "つきのいし": "Pietralunare",
    "ほのおのいし": "Pietrafocaia",
    "かみなりのいし": "Pietratuono",
    "みずのいし": "Pietraidrica",
    "リーフのいし": "Pietrafoglia",
    "まんまるいし": "Pietraovale",
    "かわらずのいし": "Pietrastante",
    "かなめいし": "Roccianima",
    "ほしのかけら": "Pezzo Stella",
    "ハートのウロコ": "Squama Cuore",
    "ねっこのカセキ": "Radifossile",
    "ツメのカセキ": "Fossilunghia",
    "かいのカセキ": "Helixfossile",
    "こうらのカセキ": "Domofossile",
    "ひみつのコハク": "Ambra antica",
    "たてのカセキ": "Fossilscudo",
    "ずがいのカセキ": "Fossilcranio",
    "きちょうなホネ": "Osso Raro",
    "ひかりのねんど": "Creta Luce",
    "くろいてっきゅう": "Ferropalla",
    "つめたいいわ": "Rocciafredda",
    "さらさらいわ": "Roccialiscia",
    "あついいわ": "Rocciacalda",
    "しめったいわ": "Rocciaumida",
    "なぞのかけらｓ": "Frammento insolito S",
    "なぞのかけらｌ": "Frammento insolito L",
    "かたいいし": "Pietradura",
    "ひのたまプレート": "Lastrarogo",
    "しずくプレート": "Lastraidro",
    "いかずちプレート": "Lastrasaetta",
    "みどりのプレート": "Lastraprato",
    "つららのプレート": "Lastragelo",
    "こぶしのプレート": "Lastrapugno",
    "もうどくプレート": "Lastrafiele",
    "だいちのプレート": "Lastrageo",
    "あおぞらプレート": "Lastracielo",
    "ふしぎのプレート": "Lastramente",
    "たまむしプレート": "Lastrabaco",
    "がんせきプレート": "Lastrapietra",
    "もののけプレート": "Lastratetra",
    "りゅうのプレート": "Lastradrakon",
    "こわもてプレート": "Lastratimore",
    "こうてつプレート": "Lastraferro",
    "せいれいプレート": "Lastraspiritello",
    "빨강구슬s": "Bilia rossa S",
    "파랑구슬s": "Bilia blu S",
    "초록구슬s": "Bilia verde S",
    "금강구슬s": "Bilia prisma S",
    "하양구슬s": "Bilia tersa S",
    "빨강구슬l": "Bilia rossa L",
    "파랑구슬l": "Bilia blu L",
    "초록구슬l": "Bilia verde L",
    "금강구슬l": "Bilia prisma L",
    "하양구슬l": "Bilia tersa L",
    "기력의조각": "Revitalizzante",
    "기력의덩어리": "Revitalizz. Max",
    "빨강조각": "Coccio Rosso",
    "파랑조각": "Coccio Blu",
    "노랑조각": "Coccio Giallo",
    "초록조각": "Coccio Verde",
    "태양의돌": "Pietrasolare",
    "달의돌": "Pietralunare",
    "불꽃의돌": "Pietrafocaia",
    "천둥의돌": "Pietratuono",
    "물의돌": "Pietraidrica",
    "리프의돌": "Pietrafoglia",
    "동글동글돌": "Pietraovale",
    "변함없는돌": "Pietrastante",
    "쐐기돌": "Roccianima",
    "별의조각": "Pezzo Stella",
    "하트비늘": "Squama Cuore",
    "뿌리화석": "Radifossile",
    "발톱화석": "Fossilunghia",
    "조개화석": "Helixfossile",
    "껍질화석": "Domofossile",
    "비밀의호박": "Ambra antica",
    "방패의화석": "Fossilscudo",
    "두개의화석": "Fossilcranio",
    "귀중한뼈": "Osso Raro",
    "빛의점토": "Creta Luce",
    "검은철구": "Ferropalla",
    "차가운바위": "Rocciafredda",
    "보송보송바위": "Roccialiscia",
    "뜨거운바위": "Rocciacalda",
    "축축한바위": "Rocciaumida",
    "수수께끼의조각s": "Frammento insolito S",
    "수수께끼의조각l": "Frammento insolito L",
    "딱딱한돌": "Pietradura",
    "불구슬플레이트": "Lastrarogo",
    "물방울플레이트": "Lastraidro",
    "우뢰플레이트": "Lastrasaetta",
    "초록플레이트": "Lastraprato",
    "고드름플레이트": "Lastragelo",
    "주먹플레이트": "Lastrapugno",
    "맹독플레이트": "Lastrafiele",
    "대지플레이트": "Lastrageo",
    "푸른하늘플레이트": "Lastracielo",
    "이상한플레이트": "Lastramente",
    "비단벌레플레이트": "Lastrabaco",
    "암석플레이트": "Lastrapietra",
    "원령플레이트": "Lastratetra",
    "용의플레이트": "Lastradrakon",
    "공포플레이트": "Lastratimore",
    "강철플레이트": "Lastraferro",
    "정령플레이트": "Lastraspiritello",
    "红玉ｓ": "Bilia rossa S",
    "蓝玉ｓ": "Bilia blu S",
    "绿玉ｓ": "Bilia verde S",
    "金刚玉ｓ": "Bilia prisma S",
    "白玉ｓ": "Bilia tersa S",
    "红玉ｌ": "Bilia rossa L",
    "蓝玉ｌ": "Bilia blu L",
    "绿玉ｌ": "Bilia verde L",
    "金刚玉ｌ": "Bilia prisma L",
    "白玉ｌ": "Bilia tersa L",
    "活力碎片": "Revitalizzante",
    "活力块": "Revitalizz. Max",
    "红色碎片": "Coccio Rosso",
    "蓝色碎片": "Coccio Blu",
    "黄色碎片": "Coccio Giallo",
    "绿色碎片": "Coccio Verde",
    "日之石": "Pietrasolare",
    "月之石": "Pietralunare",
    "火之石": "Pietrafocaia",
    "雷之石": "Pietratuono",
    "水之石": "Pietraidrica",
    "叶之石": "Pietrafoglia",
    "浑圆之石": "Pietraovale",
    "不变之石": "Pietrastante",
    "楔石": "Roccianima",
    "星星碎片": "Pezzo Stella",
    "心之鳞片": "Squama Cuore",
    "根状化石": "Radifossile",
    "爪子化石": "Fossilunghia",
    "贝壳化石": "Helixfossile",
    "甲壳化石": "Domofossile",
    "秘密琥珀": "Ambra antica",
    "盾甲化石": "Fossilscudo",
    "头盖化石": "Fossilcranio",
    "贵重骨头": "Osso Raro",
    "光之黏土": "Creta Luce",
    "黑色铁球": "Ferropalla",
    "冰冷岩石": "Rocciafredda",
    "沙沙岩石": "Roccialiscia",
    "炽热岩石": "Rocciacalda",
    "潮湿岩石": "Rocciaumida",
    "谜之碎片ｓ": "Frammento insolito S",
    "谜之碎片ｌ": "Frammento insolito L",
    "硬石头": "Pietradura",
    "火球石板": "Lastrarogo",
    "水滴石板": "Lastraidro",
    "雷电石板": "Lastrasaetta",
    "碧绿石板": "Lastraprato",
    "冰柱石板": "Lastragelo",
    "拳头石板": "Lastrapugno",
    "剧毒石板": "Lastrafiele",
    "大地石板": "Lastrageo",
    "蓝天石板": "Lastracielo",
    "神奇石板": "Lastramente",
    "玉虫石板": "Lastrabaco",
    "岩石石板": "Lastrapietra",
    "妖怪石板": "Lastratetra",
    "龙之石板": "Lastradrakon",
    "恶颜石板": "Lastratimore",
    "钢铁石板": "Lastraferro",
    "妖精石板": "Lastraspiritello",
    "紅玉ｓ": "Bilia rossa S",
    "藍玉ｓ": "Bilia blu S",
    "綠玉ｓ": "Bilia verde S",
    "金剛玉ｓ": "Bilia prisma S",
    "白玉ｓ": "Bilia tersa S",
    "紅玉ｌ": "Bilia rossa L",
    "藍玉ｌ": "Bilia blu L",
    "綠玉ｌ": "Bilia verde L",
    "金剛玉ｌ": "Bilia prisma L",
    "白玉ｌ": "Bilia tersa L",
    "活力碎片": "Revitalizzante",
    "活力塊": "Revitalizz. Max",
    "紅色碎片": "Coccio Rosso",
    "藍色碎片": "Coccio Blu",
    "黃色碎片": "Coccio Giallo",
    "綠色碎片": "Coccio Verde",
    "日之石": "Pietrasolare",
    "月之石": "Pietralunare",
    "火之石": "Pietrafocaia",
    "雷之石": "Pietratuono",
    "水之石": "Pietraidrica",
    "葉之石": "Pietrafoglia",
    "渾圓之石": "Pietraovale",
    "不變之石": "Pietrastante",
    "楔石": "Roccianima",
    "星星碎片": "Pezzo Stella",
    "心之鱗片": "Squama Cuore",
    "根狀化石": "Radifossile",
    "爪子化石": "Fossilunghia",
    "貝殼化石": "Helixfossile",
    "甲殼化石": "Domofossile",
    "秘密琥珀": "Ambra antica",
    "盾甲化石": "Fossilscudo",
    "頭蓋化石": "Fossilcranio",
    "貴重骨頭": "Osso Raro",
    "光之黏土": "Creta Luce",
    "黑色鐵球": "Ferropalla",
    "冰冷岩石": "Rocciafredda",
    "沙沙岩石": "Roccialiscia",
    "熾熱岩石": "Rocciacalda",
    "潮濕岩石": "Rocciaumida",
    "謎之碎片ｓ": "Frammento insolito S",
    "謎之碎片ｌ": "Frammento insolito L",
    "硬石頭": "Pietradura",
    "火球石板": "Lastrarogo",
    "水滴石板": "Lastraidro",
    "雷電石板": "Lastrasaetta",
    "碧綠石板": "Lastraprato",
    "冰柱石板": "Lastragelo",
    "拳頭石板": "Lastrapugno",
    "劇毒石板": "Lastrafiele",
    "大地石板": "Lastrageo",
    "藍天石板": "Lastracielo",
    "神奇石板": "Lastramente",
    "玉蟲石板": "Lastrabaco",
    "岩石石板": "Lastrapietra",
    "妖怪石板": "Lastratetra",
    "龍之石板": "Lastradrakon",
    "惡顏石板": "Lastratimore",
    "鋼鐵石板": "Lastraferro",
    "妖精石板": "Lastraspiritello",
};

// Giochi
var traduzioniGiochi = {
    "saphir": "Zaffiro",
    "rubin": "Rubino",
    "smaragd": "Smeraldo",
    "feuerrot": "RossoFuoco",
    "blattgrün": "VerdeFoglia",
    "heartgold": "HeartGold",
    "soulsilver": "SoulSilver",
    "diamant": "Diamante",
    "perl": "Perla",
    "platin": "Platino",
    "kolosseum/xd": "Colosseo/XD",
    "weiß": "Bianca",
    "schwarz": "Nera",
    "weiß 2": "Bianca 2",
    "schwarz 2": "Nera 2",
    "x": "X",
    "y": "Y",
    "alpha saphir": "Zaffiro Alpha",
    "omega rubin": "Rubino Omega",
    "sonne": "Sole",
    "mond": "Luna",
    "ultrasonne": "Ultrasole",
    "ultramond": "Ultraluna",
    "go": "GO",
    "rot": "Rossa",
    "blau [int]/grün [jp]": "Blu [INT]/Verde [JP]",
    "blau [jp]": "Blu [JP]",
    "gelb": "Gialla",
    "gold": "Oro",
    "silber": "Argento",
    "kristall": "Cristallo",
    "let's go, pikachu!": "Let's Go, Pikachu!",
    "let's go, evoli!": "Let's Go, Eevee!",
    "schwert": "Spada",
    "schild": "Scudo",
    "legenden: arceus": "Leggende: Arceus",
    "strahlender diamant": "Diamante Lucente",
    "leuchtende perle": "Perla Splendente",
    "karmesin": "Scarlatto",
    "purpur": "Violetto",
    "sapphire": "Zaffiro",
    "ruby": "Rubino",
    "emerald": "Smeraldo",
    "firered": "RossoFuoco",
    "leafgreen": "VerdeFoglia",
    "heartgold": "HeartGold",
    "soulsilver": "SoulSilver",
    "diamond": "Diamante",
    "pearl": "Perla",
    "platinum": "Platino",
    "colosseum/xd": "Colosseo/XD",
    "white": "Bianca",
    "black": "Nera",
    "white 2": "Bianca 2",
    "black 2": "Nera 2",
    "x": "X",
    "y": "Y",
    "alpha sapphire": "Zaffiro Alpha",
    "omega ruby": "Rubino Omega",
    "sun": "Sole",
    "moon": "Luna",
    "ultra sun": "Ultrasole",
    "ultra moon": "Ultraluna",
    "go": "GO",
    "red": "Rossa",
    "blue [int]/green [jp]": "Blu [INT]/Verde [JP]",
    "blue [jp]": "Blu [JP]",
    "yellow": "Gialla",
    "gold": "Oro",
    "silver": "Argento",
    "crystal": "Cristallo",
    "let's go, pikachu!": "Let's Go, Pikachu!",
    "let's go, eevee!": "Let's Go, Eevee!",
    "sword": "Spada",
    "shield": "Scudo",
    "legends: arceus": "Leggende: Arceus",
    "brilliant diamond": "Diamante Lucente",
    "shining pearl": "Perla Splendente",
    "scarlet": "Scarlatto",
    "violet": "Violetto",
    "zafiro": "Zaffiro",
    "rubí": "Rubino",
    "esmeralda": "Smeraldo",
    "rojofuego": "RossoFuoco",
    "verdehoja": "VerdeFoglia",
    "oro heartgold": "HeartGold",
    "plata soulsilver": "SoulSilver",
    "diamante": "Diamante",
    "perla": "Perla",
    "platino": "Platino",
    "colosseum/xd": "Colosseo/XD",
    "blanca": "Bianca",
    "negra": "Nera",
    "blanca 2": "Bianca 2",
    "negra 2": "Nera 2",
    "x": "X",
    "y": "Y",
    "zafiro alfa": "Zaffiro Alpha",
    "rubí omega": "Rubino Omega",
    "sol": "Sole",
    "luna": "Luna",
    "ultrasol": "Ultrasole",
    "ultraluna": "Ultraluna",
    "go": "GO",
    "roja": "Rossa",
    "azul [int]/verde [jp]": "Blu [INT]/Verde [JP]",
    "azul [jp]": "Blu [JP]",
    "amarilla": "Gialla",
    "oro": "Oro",
    "plata": "Argento",
    "cristal": "Cristallo",
    "let's go, pikachu!": "Let's Go, Pikachu!",
    "let's go, eevee!": "Let's Go, Eevee!",
    "espada": "Spada",
    "escudo": "Scudo",
    "leyendas: arceus": "Leggende: Arceus",
    "diamante brillante": "Diamante Lucente",
    "perla reluciente": "Perla Splendente",
    "escarlata": "Scarlatto",
    "púrpura": "Violetto",
    "saphir": "Zaffiro",
    "rubis": "Rubino",
    "émeraude": "Smeraldo",
    "rouge feu": "RossoFuoco",
    "vert feuille": "VerdeFoglia",
    "or heartgold": "HeartGold",
    "argent soulsilver": "SoulSilver",
    "diamant": "Diamante",
    "perle": "Perla",
    "platine": "Platino",
    "colosseum/xd": "Colosseo/XD",
    "blanche": "Bianca",
    "noire": "Nera",
    "blanche 2": "Bianca 2",
    "noire 2": "Nera 2",
    "x": "X",
    "y": "Y",
    "saphir alpha": "Zaffiro Alpha",
    "rubis oméga": "Rubino Omega",
    "soleil": "Sole",
    "lune": "Luna",
    "ultra-soleil": "Ultrasole",
    "ultra-lune": "Ultraluna",
    "go": "GO",
    "rouge": "Rossa",
    "bleue [int]/vert [jp]": "Blu [INT]/Verde [JP]",
    "bleue [jp]": "Blu [JP]",
    "jaune": "Gialla",
    "or": "Oro",
    "argent": "Argento",
    "cristal": "Cristallo",
    "let's go, pikachu": "Let's Go, Pikachu!",
    "let's go, évoli": "Let's Go, Eevee!",
    "épée": "Spada",
    "bouclier": "Scudo",
    "légendes: arceus": "Leggende: Arceus",
    "diamant étincelant": "Diamante Lucente",
    "perle scintillante": "Perla Splendente",
    "écarlate": "Scarlatto",
    "violet": "Violetto",
    "サファイア": "Zaffiro",
    "ルビー": "Rubino",
    "エメラルド": "Smeraldo",
    "ファイアレッド": "RossoFuoco",
    "リーフグリーン": "VerdeFoglia",
    "ハートゴールド": "HeartGold",
    "ソウルシルバー": "SoulSilver",
    "ダイヤモンド": "Diamante",
    "パール": "Perla",
    "プラチナ": "Platino",
    "コロシアム/xd": "Colosseo/XD",
    "ホワイト": "Bianca",
    "ブラック": "Nera",
    "ホワイト 2": "Bianca 2",
    "ブラック 2": "Nera 2",
    "x": "X",
    "y": "Y",
    "アルファサファイア": "Zaffiro Alpha",
    "オメガルビー": "Rubino Omega",
    "サン": "Sole",
    "ムーン": "Luna",
    "ウルトラサン": "Ultrasole",
    "ウルトラムーン": "Ultraluna",
    "go": "GO",
    "赤": "Rossa",
    "青 [int]/緑 [jp]": "Blu [INT]/Verde [JP]",
    "青 [jp]": "Blu [JP]",
    "黄": "Gialla",
    "金": "Oro",
    "銀": "Argento",
    "クリスタル": "Cristallo",
    "let's go! ピカチュウ": "Let's Go, Pikachu!",
    "let's go! イーブイ": "Let's Go, Eevee!",
    "ソード": "Spada",
    "シールド": "Scudo",
    "legends アルセウス": "Leggende: Arceus",
    "ブリリアントダイヤモンド": "Diamante Lucente",
    "シャイニングパール": "Perla Splendente",
    "スカーレット": "Scarlatto",
    "バイオレット": "Violetto",
    "사파이어": "Zaffiro",
    "루비": "Rubino",
    "에메랄드": "Smeraldo",
    "파이어레드": "RossoFuoco",
    "리프그린": "VerdeFoglia",
    "하트골드": "HeartGold",
    "소울실버": "SoulSilver",
    "디아루가": "Diamante",
    "펄기아": "Perla",
    "pt기라티나": "Platino",
    "콜로세움/xd": "Colosseo/XD",
    "화이트": "Bianca",
    "블랙": "Nera",
    "화이트 2": "Bianca 2",
    "블랙 2": "Nera 2",
    "x": "X",
    "y": "Y",
    "알파사파이어": "Zaffiro Alpha",
    "오메가루비": "Rubino Omega",
    "썬": "Sole",
    "문": "Luna",
    "울트라썬": "Ultrasole",
    "울트라문": "Ultraluna",
    "고": "GO",
    "레드": "Rossa",
    "블루 [int]/그린 [jp]": "Blu [INT]/Verde [JP]",
    "블루 [jp]": "Blu [JP]",
    "피카츄": "Gialla",
    "금": "Oro",
    "은": "Argento",
    "크리스탈": "Cristallo",
    "레츠고! 피카츄": "Let's Go, Pikachu!",
    "레츠고! 이브이": "Let's Go, Eevee!",
    "소드": "Spada",
    "실드": "Scudo",
    "legends 아르세우스": "Leggende: Arceus",
    "브릴리언트 다이아몬드": "Diamante Lucente",
    "샤이닝 펄": "Perla Splendente",
    "스칼렛": "Scarlatto",
    "바이올렛": "Violetto",
    "蓝宝石": "Zaffiro",
    "红宝石": "Rubino",
    "绿宝石": "Smeraldo",
    "火红": "RossoFuoco",
    "叶绿": "VerdeFoglia",
    "心金": "HeartGold",
    "魂银": "SoulSilver",
    "钻石": "Diamante",
    "珍珠": "Perla",
    "白金": "Platino",
    "竞技场/xd": "Colosseo/XD",
    "白": "Bianca",
    "黑": "Nera",
    "白 2": "Bianca 2",
    "黑 2": "Nera 2",
    "x": "X",
    "y": "Y",
    "始源蓝宝石": "Zaffiro Alpha",
    "终极红宝石": "Rubino Omega",
    "太阳": "Sole",
    "月亮": "Luna",
    "究极之日": "Ultrasole",
    "究极之月": "Ultraluna",
    "go": "GO",
    "红": "Rossa",
    "蓝 [国际]/绿 [日]": "Blu [INT]/Verde [JP]",
    "蓝 [日]": "Blu [JP]",
    "黄": "Gialla",
    "金": "Oro",
    "银": "Argento",
    "水晶": "Cristallo",
    "let's go！皮卡丘": "Let's Go, Pikachu!",
    "let's go！伊布": "Let's Go, Eevee!",
    "剑": "Spada",
    "盾": "Scudo",
    "传说 阿尔宙斯": "Leggende: Arceus",
    "晶灿钻石": "Diamante Lucente",
    "明亮珍珠": "Perla Splendente",
    "朱": "Scarlatto",
    "紫": "Violetto",
    "藍寶石": "Zaffiro",
    "紅寶石": "Rubino",
    "綠寶石": "Smeraldo",
    "火紅": "RossoFuoco",
    "葉綠": "VerdeFoglia",
    "心金": "HeartGold",
    "魂銀": "SoulSilver",
    "鑽石": "Diamante",
    "珍珠": "Perla",
    "白金": "Platino",
    "圓形競技場/xd旋風": "Colosseo/XD",
    "白": "Bianca",
    "黑": "Nera",
    "白 2": "Bianca 2",
    "黑 2": "Nera 2",
    "x": "X",
    "y": "Y",
    "阿爾法藍寶石": "Zaffiro Alpha",
    "歐米加紅寶石": "Rubino Omega",
    "太陽": "Sole",
    "月亮": "Luna",
    "究極之日": "Ultrasole",
    "究極之月": "Ultraluna",
    "go": "GO",
    "紅": "Rossa",
    "藍 [國際]/綠 [日]": "Blu [INT]/Verde [JP]",
    "藍 [日]": "Blu [JP]",
    "皮卡丘（黃）": "Gialla",
    "金": "Oro",
    "銀": "Argento",
    "水晶": "Cristallo",
    "let's go！皮卡丘": "Let's Go, Pikachu!",
    "let's go！伊布": "Let's Go, Eevee!",
    "劍": "Spada",
    "盾": "Scudo",
    "傳說：阿爾宙斯": "Leggende: Arceus",
    "晶燦鑽石": "Diamante Lucente",
    "明亮珍珠": "Perla Splendente",
    "朱": "Scarlatto",
    "紫": "Violetto",
};

// Sfondi box
var traduzioniSfondi = {
    "wald": "Foresta",
    "stadt": "Città",
    "wüste": "Deserto",
    "steppe": "Savana",
    "geröll": "Rocce",
    "vulkan": "Vulcano",
    "schnee": "Neve",
    "höhle": "Grotta",
    "strand": "Spiaggia",
    "tiefsee": "Fondale",
    "fluss": "Fiume",
    "himmel": "Cielo",
    "poké-center": "Centro Pokémon",
    "metall": "Metallo",
    "kariert": "Quadretti",
    "weiß": "Semplice",
    "spezialmotiv 1": "Speciale 1",
    "spezialmotiv 2": "Speciale 2",
    "spezialmotiv 3": "Speciale 3",
    "spezialmotiv 4": "Speciale 4",
    "spezialmotiv 5": "Speciale 5",
    "spezialmotiv 6": "Speciale 6",
    "spezialmotiv 7": "Speciale 7",
    "spezialmotiv 8": "Speciale 8",
    "spezialmotiv 9": "Speciale 9",
    "spezialmotiv 10": "Speciale 10",
    "spezialmotiv 11": "Speciale 11",
    "spezialmotiv 12": "Speciale 12",
    "spezialmotiv 13": "Speciale 13",
    "spezialmotiv 14": "Speciale 14",
    "spezialmotiv 15": "Speciale 15",
    "spezialmotiv 16": "Speciale 16",
    "forest": "Foresta",
    "city": "Città",
    "desert": "Deserto",
    "savanna": "Savana",
    "crag": "Rocce",
    "volcano": "Vulcano",
    "snow": "Neve",
    "cave": "Grotta",
    "beach": "Spiaggia",
    "seafloor": "Fondale",
    "river": "Fiume",
    "sky": "Cielo",
    "poké center": "Centro Pokémon",
    "machine": "Metallo",
    "checks": "Quadretti",
    "simple": "Semplice",
    "special 1": "Speciale 1",
    "special 2": "Speciale 2",
    "special 3": "Speciale 3",
    "special 4": "Speciale 4",
    "special 5": "Speciale 5",
    "special 6": "Speciale 6",
    "special 7": "Speciale 7",
    "special 8": "Speciale 8",
    "special 9": "Speciale 9",
    "special 10": "Speciale 10",
    "special 11": "Speciale 11",
    "special 12": "Speciale 12",
    "special 13": "Speciale 13",
    "special 14": "Speciale 14",
    "special 15": "Speciale 15",
    "special 16": "Speciale 16",
    "bosque": "Foresta",
    "ciudad": "Città",
    "desierto": "Deserto",
    "sabana": "Savana",
    "montaña": "Rocce",
    "volcán": "Vulcano",
    "nieve": "Neve",
    "cueva": "Grotta",
    "playa": "Spiaggia",
    "mar": "Fondale",
    "río": "Fiume",
    "cielo": "Cielo",
    "centro pokémon": "Centro Pokémon",
    "máquina": "Metallo",
    "cuadros": "Quadretti",
    "sencillo": "Semplice",
    "especial 1": "Speciale 1",
    "especial 2": "Speciale 2",
    "especial 3": "Speciale 3",
    "especial 4": "Speciale 4",
    "especial 5": "Speciale 5",
    "especial 6": "Speciale 6",
    "especial 7": "Speciale 7",
    "especial 8": "Speciale 8",
    "especial 9": "Speciale 9",
    "especial 10": "Speciale 10",
    "especial 11": "Speciale 11",
    "especial 12": "Speciale 12",
    "especial 13": "Speciale 13",
    "especial 14": "Speciale 14",
    "especial 15": "Speciale 15",
    "especial 16": "Speciale 16",
    "forêt": "Foresta",
    "ville": "Città",
    "désert": "Deserto",
    "savane": "Savana",
    "rochers": "Rocce",
    "volcan": "Vulcano",
    "neige": "Neve",
    "grotte": "Grotta",
    "plage": "Spiaggia",
    "mer": "Fondale",
    "rivière": "Fiume",
    "ciel": "Cielo",
    "centre pokémon": "Centro Pokémon",
    "métal": "Metallo",
    "vichy": "Quadretti",
    "uni": "Semplice",
    "spécial 1": "Speciale 1",
    "spécial 2": "Speciale 2",
    "spécial 3": "Speciale 3",
    "spécial 4": "Speciale 4",
    "spécial 5": "Speciale 5",
    "spécial 6": "Speciale 6",
    "spécial 7": "Speciale 7",
    "spécial 8": "Speciale 8",
    "spécial 9": "Speciale 9",
    "spécial 10": "Speciale 10",
    "spécial 11": "Speciale 11",
    "spécial 12": "Speciale 12",
    "spécial 13": "Speciale 13",
    "spécial 14": "Speciale 14",
    "spécial 15": "Speciale 15",
    "spécial 16": "Speciale 16",
    "もり": "Foresta",
    "シティ": "Città",
    "さばく": "Deserto",
    "サバンナ": "Savana",
    "いわやま": "Rocce",
    "かざん": "Vulcano",
    "ゆきやま": "Neve",
    "どうくつ": "Grotta",
    "うみべ": "Spiaggia",
    "かいてい": "Fondale",
    "かわ": "Fiume",
    "そら": "Cielo",
    "ポケセン": "Centro Pokémon",
    "きんぞく": "Metallo",
    "チェック": "Quadretti",
    "シンプル": "Semplice",
    "スペシャル１": "Speciale 1",
    "スペシャル２": "Speciale 2",
    "スペシャル３": "Speciale 3",
    "スペシャル４": "Speciale 4",
    "スペシャル５": "Speciale 5",
    "スペシャル６": "Speciale 6",
    "スペシャル７": "Speciale 7",
    "スペシャル８": "Speciale 8",
    "スペシャル９": "Speciale 9",
    "スペシャル１０": "Speciale 10",
    "スペシャル１１": "Speciale 11",
    "スペシャル１２": "Speciale 12",
    "スペシャル１３": "Speciale 13",
    "スペシャル１４": "Speciale 14",
    "スペシャル１５": "Speciale 15",
    "スペシャル１６": "Speciale 16",
    "숲": "Foresta",
    "시티": "Città",
    "사막": "Deserto",
    "사바나": "Savana",
    "바위산": "Rocce",
    "화산": "Vulcano",
    "설산": "Neve",
    "동굴": "Grotta",
    "바닷가": "Spiaggia",
    "해저": "Fondale",
    "강": "Fiume",
    "하늘": "Cielo",
    "포켓센": "Centro Pokémon",
    "금속": "Metallo",
    "체크": "Quadretti",
    "심플": "Semplice",
    "스페셜1": "Speciale 1",
    "스페셜2": "Speciale 2",
    "스페셜3": "Speciale 3",
    "스페셜4": "Speciale 4",
    "스페셜5": "Speciale 5",
    "스페셜6": "Speciale 6",
    "스페셜7": "Speciale 7",
    "스페셜8": "Speciale 8",
    "스페셜9": "Speciale 9",
    "스페셜10": "Speciale 10",
    "스페셜11": "Speciale 11",
    "스페셜12": "Speciale 12",
    "스페셜13": "Speciale 13",
    "스페셜14": "Speciale 14",
    "스페셜15": "Speciale 15",
    "스페셜16": "Speciale 16",
    "森林": "Foresta",
    "城市": "Città",
    "沙漠": "Deserto",
    "热带草原": "Savana",
    "石山": "Rocce",
    "火山": "Vulcano",
    "雪山": "Neve",
    "洞窟": "Grotta",
    "海滨": "Spiaggia",
    "海底": "Fondale",
    "河川": "Fiume",
    "天空": "Cielo",
    "宝可梦中心": "Centro Pokémon",
    "金属": "Metallo",
    "方格": "Quadretti",
    "朴素": "Semplice",
    "特典１": "Speciale 1",
    "特典２": "Speciale 2",
    "特典３": "Speciale 3",
    "特典４": "Speciale 4",
    "特典５": "Speciale 5",
    "特典６": "Speciale 6",
    "特典７": "Speciale 7",
    "特典８": "Speciale 8",
    "特典９": "Speciale 9",
    "特典１０": "Speciale 10",
    "特典１１": "Speciale 11",
    "特典１２": "Speciale 12",
    "特典１３": "Speciale 13",
    "特典１４": "Speciale 14",
    "特典１５": "Speciale 15",
    "特典１６": "Speciale 16",
    "森林": "Foresta",
    "城市": "Città",
    "沙漠": "Deserto",
    "熱帶草原": "Savana",
    "石山": "Rocce",
    "火山": "Vulcano",
    "雪山": "Neve",
    "洞窟": "Grotta",
    "海濱": "Spiaggia",
    "海底": "Fondale",
    "河川": "Fiume",
    "天空": "Cielo",
    "寶可夢中心": "Centro Pokémon",
    "金屬": "Metallo",
    "方格": "Quadretti",
    "樸素": "Semplice",
    "特典１": "Speciale 1",
    "特典２": "Speciale 2",
    "特典３": "Speciale 3",
    "特典４": "Speciale 4",
    "特典５": "Speciale 5",
    "特典６": "Speciale 6",
    "特典７": "Speciale 7",
    "特典８": "Speciale 8",
    "特典９": "Speciale 9",
    "特典１０": "Speciale 10",
    "特典１１": "Speciale 11",
    "特典１２": "Speciale 12",
    "特典１３": "Speciale 13",
    "特典１４": "Speciale 14",
    "特典１５": "Speciale 15",
    "特典１６": "Speciale 16",
};

// Regioni
var traduzioniRegioni = {
    // Giapponese --> Italiano
    "カントー地方": "Kanto",
    "ジョウト地方": "Johto",
    "ホウエン地方": "Hoenn",
    "シンオウ地方 ": "Sinnoh",
    "イッシュ地方": "Unima",
    "カロス地方": "Kalos",
    "アローラ地方 ": "Alola",
    "ガラル地方": "Galar",
    "ヒスイ地方": "Hisui",
    "パルデア地方": "Paldea",
    // Extra Giapponese
    "ナナシマ": "Settipelago",
    "ヨロイ": "Isola dell'Armatura",
    "カンムリせつげん": "Landa Corona",
    "キタカミ": "Nordivia",
    // Inglese --> Italiano
    "unova": "Unima",
    // Extra Inglese
    "sevii islands": "Settipelago",
    "isle of armor": "Isola dell'Armatura",
    "crown tundra": "Landa Corona",
    "kitakami": "Nordivia",
};

// Classi Allenatori
var traduzioniClassiAllenatori = {
    // Prima generazione
    "beauty": "Bellezza",
    "biker": "Centauro",
    "bird keeper (m)": "Avicoltore (♂)",
    "bird keeper (s)": "Avicoltrice (♀)",
    "black belt": "Cinturanera",
    "bug catcher": "Pigliamosche",
    "burglar": "Scassinatore",
    "channeler": "Medium",
    "ace trainer 1": "Fantallen.",
    "ace trainer (m)": "Fantallenatore",
    "ace trainer (s)": "Fantallenatrice",
    "roughneck": "Zuccapelata",
    "engineer": "Meccanico",
    "fisher (m)": "Pescatore",
    "fisher (s)": "Pescatrice",
    "pi": "Rischiatutto",
    "gentleman": "Gentiluomo",
    "hiker 1": "Avventuriero",
    "hiker 2": "Montanaro",
    "camper 1": "Campeggiatore",
    "camper 2": "Campeggista",
    "camper 3": "Allen. Jr♂",
    "picnicker 1": "Picnic Girl",
    "picnicker 2": "Allen. Jr♀",
    "juggler": "Giocoliere",
    "lass 1": "Pupa",
    "lass 2": "Teenager",
    "poké maniac": "Pokéfanatico",
    "psychic 1": "Sensitivo",
    "psychic 2": "Psiche",
    "rocker 1": "Tecnico del suono",
    "rocker 2": "Rockettaro",
    "team rocket grunt 1": "Rocket",
    "team rocket grunt 2": "Recluta, Rocket",
    "team rocket grunt 3": "Recluta, Team Rocket",
    "sailor": "Marinaio",
    "scientist (m)": "Scienziato",
    "scientist (f)": "Scienziata",
    "scientist 3": "Ricercatore",
    "super nerd": "Cervellone",
    "swimmer (m)": "Nuotatore",
    "swimmer (f)": "Nuotatrice",
    "tamer": "Domatore",
    "youngster 1": "Bullo",
    "youngster 2": "Marmocchio",
    "chief": "Chief",
    // Seconda Generazione
    "boarder": "Snowboarder",
    "pokémon champion (m)": "Campione",
    "pokémon champion (f)": "Campionessa",
    "elite four": "Superquattro",
    "firebreather": "Mangiafuoco",
    "guitarist": "Chitarrista",
    "kimono girl": "Kimono Girl",
    "gym leader": "Capopalestra",
    "medium 1": "Sciamana",
    "medium 2": "Sensitiva",
    "police officer": "Guardia",
    "poké fan 1": "PokéFan",
    "poké fan 2": "Pokéfan",
    "executive 1": "Generale Team Rocket",
    "executive 2": "Generale Rocket",
    "executive 3": "Tenente, Team Rocket",
    "executive 4": "Generale,Rocket",
    "sage": "Saggio",
    "school kid (m)": "Scolaro",
    "school kid (f)": "Scolara",
    "skier (m)": "Sciatore",
    "skier (f)": "Sciatrice",
    "teacher": "Insegnante",
    "twins": "Gemelle",
    "mystery man 1": "Fantallen.",
    "mystery man 2": "Sig. Mistero",
    "mystery man 3": "Uomo losco",
    // Terza Generazione
    "aqua admin": "Idrotenente",
    "aqua leader": "Capo Idro",
    "aroma lady": "Profumina",
    "battle girl": "Combat Girl",
    "bug maniac": "Insettologo",
    "collector 1": "Cercapokémon",
    "collector 2": "Cerca PKMN",
    "dragon tamer": "Domadraghi",
    "expert": "Specialista",
    "hex maniac": "Streghetta",
    "interviewer": "Reporter",
    "kindler": "Brandifuoco",
    "lady": "Lady",
    "magma admin": "Magmatenente",
    "magma leader": "Capo Magma",
    "ninja boy": "Ninja Boy",
    "old couple": "Coppiarzilla",
    "parasol lady": "Ombrellina",
    "pkmn breeder 1": "AllevaPKMN",
    "pkmn breeder 2": "Allevapokémon",
    "pkmn ranger 1": "PKMN Scout",
    "pkmn ranger 2": "PKMN Ranger",
    "pkmn ranger 3": "Pokémon Ranger",
    "rich boy": "Elegantone",
    "ruin maniac": "Scoprirovine",
    "sis and bro": "Fratellini",
    "sr. and jr. 1": "Senior & Jr",
    "sr. and jr. 2": "Senior & Junior",
    "team aqua grunt 1": "Recluta Idro",
    "team aqua grunt 2": "Recluta Team Idro",
    "team magma grunt 1": "Recluta Magma",
    "team magma grunt 2": "Recluta Team Magma",
    "triathlete": "Triatleta",
    "tuber (m)": "Ciambellino",
    "tuber (f)": "Ciambellina",
    "winstrate": "Vinci",
    "young couple": "Coppietta",
    // Quarta Generazione
    "artist": "Artista",
    "belle & pa": "Ranch Family",
    "cameraman": "Cameraman",
    "clown": "Clown",
    "commander 1": "Comandante",
    "commander 2": "Comandante Galassia",
    "cowgirl": "Cowgirl",
    "cyclist": "Ciclista",
    "double team": "Doppioteam",
    "team galactic grunt 1": "Recluta Galassia",
    "team galactic grunt 2": "Recluta Team Galassia",
    "galactic boss 1": "Capogalassia",
    "galactic boss 2": "Capo Galassia",
    "idol": "Pop Star",
    "jogger": "Podista",
    "poké kid (m)": "Poké Bimbo (♂)",
    "poké kid (f)": "Poké Bimba (♀)",
    "rancher": "Fattore",
    "reporter": "Inviata",
    "socialite": "Madame",
    "veteran (m)": "Veterano (♂)",
    "veteran (f)": "Veterana (♀)",
    "waiter": "Cameriere",
    "waitress": "Cameriera",
    // Quinta Generazione
    // Sesta Generazione
    // Settima Generazione
    // Ottava Generazione
    // Nona Generazione
};

var Numero_in_Nome = {
    "0001": "Bulbasaur",
    "2": "Ivysaur",
    "3": "Venusaur",
    "4": "Charmander",
    "5": "Charmeleon",
    "6": "Charizard",
    "7": "Squirtle",
    "8": "Wartortle",
    "9": "Blastoise",
    "10": "Caterpie",
    "11": "Metapod",
    "12": "Butterfree",
    "13": "Weedle",
    "14": "Kakuna",
    "15": "Beedrill",
    "16": "Pidgey",
    "17": "Pidgeotto",
    "18": "Pidgeot",
    "19": "Rattata",
    "20": "Raticate",
    "21": "Spearow",
    "22": "Fearow",
    "23": "Ekans",
    "24": "Arbok",
    "25": "Pikachu",
    "26": "Raichu",
    "27": "Sandshrew",
    "28": "Sandslash",
    "29": "Nidoran♀",
    "30": "Nidorina",
    "31": "Nidoqueen",
    "32": "Nidoran♂",
    "33": "Nidorino",
    "34": "Nidoking",
    "35": "Clefairy",
    "36": "Clefable",
    "37": "Vulpix",
    "38": "Ninetales",
    "39": "Jigglypuff",
    "40": "Wigglytuff",
    "41": "Zubat",
    "42": "Golbat",
    "43": "Oddish",
    "44": "Gloom",
    "45": "Vileplume",
    "46": "Paras",
    "47": "Parasect",
    "48": "Venonat",
    "49": "Venomoth",
    "50": "Diglett",
    "51": "Dugtrio",
    "52": "Meowth",
    "53": "Persian",
    "54": "Psyduck",
    "55": "Golduck",
    "56": "Mankey",
    "57": "Primeape",
    "58": "Growlithe",
    "59": "Arcanine",
    "60": "Poliwag",
    "61": "Poliwhirl",
    "62": "Poliwrath",
    "63": "Abra",
    "64": "Kadabra",
    "65": "Alakazam",
    "66": "Machop",
    "67": "Machoke",
    "68": "Machamp",
    "69": "Bellsprout",
    "70": "Weepinbell",
    "71": "Victreebel",
    "72": "Tentacool",
    "73": "Tentacruel",
    "74": "Geodude",
    "75": "Graveler",
    "76": "Golem",
    "77": "Ponyta",
    "78": "Rapidash",
    "79": "Slowpoke",
    "80": "Slowbro",
    "81": "Magnemite",
    "82": "Magneton",
    "83": "Farfetch’d",
    "84": "Doduo",
    "85": "Dodrio",
    "86": "Seel",
    "87": "Dewgong",
    "88": "Grimer",
    "89": "Muk",
    "90": "Shellder",
    "91": "Cloyster",
    "92": "Gastly",
    "93": "Haunter",
    "94": "Gengar",
    "95": "Onix",
    "96": "Drowzee",
    "97": "Hypno",
    "98": "Krabby",
    "99": "Kingler",
    "100": "Voltorb",
    "101": "Electrode",
    "102": "Exeggcute",
    "103": "Exeggutor",
    "104": "Cubone",
    "105": "Marowak",
    "106": "Hitmonlee",
    "107": "Hitmonchan",
    "108": "Lickitung",
    "109": "Koffing",
    "110": "Weezing",
    "111": "Rhyhorn",
    "112": "Rhydon",
    "113": "Chansey",
    "114": "Tangela",
    "115": "Kangaskhan",
    "116": "Horsea",
    "117": "Seadra",
    "118": "Goldeen",
    "119": "Seaking",
    "120": "Staryu",
    "121": "Starmie",
    "122": "Mr. Mime",
    "123": "Scyther",
    "124": "Jynx",
    "125": "Electabuzz",
    "126": "Magmar",
    "127": "Pinsir",
    "128": "Tauros",
    "129": "Magikarp",
    "130": "Gyarados",
    "131": "Lapras",
    "132": "Ditto",
    "133": "Eevee",
    "134": "Vaporeon",
    "135": "Jolteon",
    "136": "Flareon",
    "137": "Porygon",
    "138": "Omanyte",
    "139": "Omastar",
    "140": "Kabuto",
    "141": "Kabutops",
    "142": "Aerodactyl",
    "143": "Snorlax",
    "144": "Articuno",
    "145": "Zapdos",
    "146": "Moltres",
    "147": "Dratini",
    "148": "Dragonair",
    "149": "Dragonite",
    "150": "Mewtwo",
    "151": "Mew",
    "152": "Chikorita",
    "153": "Bayleef",
    "154": "Meganium",
    "155": "Cyndaquil",
    "156": "Quilava",
    "157": "Typhlosion",
    "158": "Totodile",
    "159": "Croconaw",
    "160": "Feraligatr",
    "161": "Sentret",
    "162": "Furret",
    "163": "Hoothoot",
    "164": "Noctowl",
    "165": "Ledyba",
    "166": "Ledian",
    "167": "Spinarak",
    "168": "Ariados",
    "169": "Crobat",
    "170": "Chinchou",
    "171": "Lanturn",
    "172": "Pichu",
    "173": "Cleffa",
    "174": "Igglybuff",
    "175": "Togepi",
    "176": "Togetic",
    "177": "Natu",
    "178": "Xatu",
    "179": "Mareep",
    "180": "Flaaffy",
    "181": "Ampharos",
    "182": "Bellossom",
    "183": "Marill",
    "184": "Azumarill",
    "185": "Sudowoodo",
    "186": "Politoed",
    "187": "Hoppip",
    "188": "Skiploom",
    "189": "Jumpluff",
    "190": "Aipom",
    "191": "Sunkern",
    "192": "Sunflora",
    "193": "Yanma",
    "194": "Wooper",
    "195": "Quagsire",
    "196": "Espeon",
    "197": "Umbreon",
    "198": "Murkrow",
    "199": "Slowking",
    "200": "Misdreavus",
    "201": "Unown",
    "202": "Wobbuffet",
    "203": "Girafarig",
    "204": "Pineco",
    "205": "Forretress",
    "206": "Dunsparce",
    "207": "Gligar",
    "208": "Steelix",
    "209": "Snubbull",
    "210": "Granbull",
    "211": "Qwilfish",
    "212": "Scizor",
    "213": "Shuckle",
    "214": "Heracross",
    "215": "Sneasel",
    "216": "Teddiursa",
    "217": "Ursaring",
    "218": "Slugma",
    "219": "Magcargo",
    "220": "Swinub",
    "221": "Piloswine",
    "222": "Corsola",
    "223": "Remoraid",
    "224": "Octillery",
    "225": "Delibird",
    "226": "Mantine",
    "227": "Skarmory",
    "228": "Houndour",
    "229": "Houndoom",
    "230": "Kingdra",
    "231": "Phanpy",
    "232": "Donphan",
    "233": "Porygon2",
    "234": "Stantler",
    "235": "Smeargle",
    "236": "Tyrogue",
    "237": "Hitmontop",
    "238": "Smoochum",
    "239": "Elekid",
    "240": "Magby",
    "241": "Miltank",
    "242": "Blissey",
    "243": "Raikou",
    "244": "Entei",
    "245": "Suicune",
    "246": "Larvitar",
    "247": "Pupitar",
    "248": "Tyranitar",
    "249": "Lugia",
    "250": "Ho-Oh",
    "251": "Celebi",
    "252": "Treecko",
    "253": "Grovyle",
    "254": "Sceptile",
    "255": "Torchic",
    "256": "Combusken",
    "257": "Blaziken",
    "258": "Mudkip",
    "259": "Marshtomp",
    "260": "Swampert",
    "261": "Poochyena",
    "262": "Mightyena",
    "263": "Zigzagoon",
    "264": "Linoone",
    "265": "Wurmple",
    "266": "Silcoon",
    "267": "Beautifly",
    "268": "Cascoon",
    "269": "Dustox",
    "270": "Lotad",
    "271": "Lombre",
    "272": "Ludicolo",
    "273": "Seedot",
    "274": "Nuzleaf",
    "275": "Shiftry",
    "276": "Taillow",
    "277": "Swellow",
    "278": "Wingull",
    "279": "Pelipper",
    "280": "Ralts",
    "281": "Kirlia",
    "282": "Gardevoir",
    "283": "Surskit",
    "284": "Masquerain",
    "285": "Shroomish",
    "286": "Breloom",
    "287": "Slakoth",
    "288": "Vigoroth",
    "289": "Slaking",
    "290": "Nincada",
    "291": "Ninjask",
    "292": "Shedinja",
    "293": "Whismur",
    "294": "Loudred",
    "295": "Exploud",
    "296": "Makuhita",
    "297": "Hariyama",
    "298": "Azurill",
    "299": "Nosepass",
    "300": "Skitty",
    "301": "Delcatty",
    "302": "Sableye",
    "303": "Mawile",
    "304": "Aron",
    "305": "Lairon",
    "306": "Aggron",
    "307": "Meditite",
    "308": "Medicham",
    "309": "Electrike",
    "310": "Manectric",
    "311": "Plusle",
    "312": "Minun",
    "313": "Volbeat",
    "314": "Illumise",
    "315": "Roselia",
    "316": "Gulpin",
    "317": "Swalot",
    "318": "Carvanha",
    "319": "Sharpedo",
    "320": "Wailmer",
    "321": "Wailord",
    "322": "Numel",
    "323": "Camerupt",
    "324": "Torkoal",
    "325": "Spoink",
    "326": "Grumpig",
    "327": "Spinda",
    "328": "Trapinch",
    "329": "Vibrava",
    "330": "Flygon",
    "331": "Cacnea",
    "332": "Cacturne",
    "333": "Swablu",
    "334": "Altaria",
    "335": "Zangoose",
    "336": "Seviper",
    "337": "Lunatone",
    "338": "Solrock",
    "339": "Barboach",
    "340": "Whiscash",
    "341": "Corphish",
    "342": "Crawdaunt",
    "343": "Baltoy",
    "344": "Claydol",
    "345": "Lileep",
    "346": "Cradily",
    "347": "Anorith",
    "348": "Armaldo",
    "349": "Feebas",
    "350": "Milotic",
    "351": "Castform",
    "352": "Kecleon",
    "353": "Shuppet",
    "354": "Banette",
    "355": "Duskull",
    "356": "Dusclops",
    "357": "Tropius",
    "358": "Chimecho",
    "359": "Absol",
    "360": "Wynaut",
    "361": "Snorunt",
    "362": "Glalie",
    "363": "Spheal",
    "364": "Sealeo",
    "365": "Walrein",
    "366": "Clamperl",
    "367": "Huntail",
    "368": "Gorebyss",
    "369": "Relicanth",
    "370": "Luvdisc",
    "371": "Bagon",
    "372": "Shelgon",
    "373": "Salamence",
    "374": "Beldum",
    "375": "Metang",
    "376": "Metagross",
    "377": "Regirock",
    "378": "Regice",
    "379": "Registeel",
    "380": "Latias",
    "381": "Latios",
    "382": "Kyogre",
    "383": "Groudon",
    "384": "Rayquaza",
    "385": "Jirachi",
    "386": "Deoxys",
    "387": "Turtwig",
    "388": "Grotle",
    "389": "Torterra",
    "390": "Chimchar",
    "391": "Monferno",
    "392": "Infernape",
    "393": "Piplup",
    "394": "Prinplup",
    "395": "Empoleon",
    "396": "Starly",
    "397": "Staravia",
    "398": "Staraptor",
    "399": "Bidoof",
    "400": "Bibarel",
    "401": "Kricketot",
    "402": "Kricketune",
    "403": "Shinx",
    "404": "Luxio",
    "405": "Luxray",
    "406": "Budew",
    "407": "Roserade",
    "408": "Cranidos",
    "409": "Rampardos",
    "410": "Shieldon",
    "411": "Bastiodon",
    "412": "Burmy",
    "413": "Wormadam",
    "414": "Mothim",
    "415": "Combee",
    "416": "Vespiquen",
    "417": "Pachirisu",
    "418": "Buizel",
    "419": "Floatzel",
    "420": "Cherubi",
    "421": "Cherrim",
    "422": "Shellos",
    "423": "Gastrodon",
    "424": "Ambipom",
    "425": "Drifloon",
    "426": "Drifblim",
    "427": "Buneary",
    "428": "Lopunny",
    "429": "Mismagius",
    "430": "Honchkrow",
    "431": "Glameow",
    "432": "Purugly",
    "433": "Chingling",
    "434": "Stunky",
    "435": "Skuntank",
    "436": "Bronzor",
    "437": "Bronzong",
    "438": "Bonsly",
    "439": "Mime Jr.",
    "440": "Happiny",
    "441": "Chatot",
    "442": "Spiritomb",
    "443": "Gible",
    "444": "Gabite",
    "445": "Garchomp",
    "446": "Munchlax",
    "447": "Riolu",
    "448": "Lucario",
    "449": "Hippopotas",
    "450": "Hippowdon",
    "451": "Skorupi",
    "452": "Drapion",
    "453": "Croagunk",
    "454": "Toxicroak",
    "455": "Carnivine",
    "456": "Finneon",
    "457": "Lumineon",
    "458": "Mantyke",
    "459": "Snover",
    "460": "Abomasnow",
    "461": "Weavile",
    "462": "Magnezone",
    "463": "Lickilicky",
    "464": "Rhyperior",
    "465": "Tangrowth",
    "466": "Electivire",
    "467": "Magmortar",
    "468": "Togekiss",
    "469": "Yanmega",
    "470": "Leafeon",
    "471": "Glaceon",
    "472": "Gliscor",
    "473": "Mamoswine",
    "474": "Porygon-Z",
    "475": "Gallade",
    "476": "Probopass",
    "477": "Dusknoir",
    "478": "Froslass",
    "479": "Rotom",
    "480": "Uxie",
    "481": "Mesprit",
    "482": "Azelf",
    "483": "Dialga",
    "484": "Palkia",
    "485": "Heatran",
    "486": "Regigigas",
    "487": "Giratina",
    "488": "Cresselia",
    "489": "Phione",
    "490": "Manaphy",
    "491": "Darkrai",
    "492": "Shaymin",
    "493": "Arceus",
    "494": "Victini",
    "495": "Snivy",
    "496": "Servine",
    "497": "Serperior",
    "498": "Tepig",
    "499": "Pignite",
    "500": "Emboar",
    "501": "Oshawott",
    "502": "Dewott",
    "503": "Samurott",
    "504": "Patrat",
    "505": "Watchog",
    "506": "Lillipup",
    "507": "Herdier",
    "508": "Stoutland",
    "509": "Purrloin",
    "510": "Liepard",
    "511": "Pansage",
    "512": "Simisage",
    "513": "Pansear",
    "514": "Simisear",
    "515": "Panpour",
    "516": "Simipour",
    "517": "Munna",
    "518": "Musharna",
    "519": "Pidove",
    "520": "Tranquill",
    "521": "Unfezant",
    "522": "Blitzle",
    "523": "Zebstrika",
    "524": "Roggenrola",
    "525": "Boldore",
    "526": "Gigalith",
    "527": "Woobat",
    "528": "Swoobat",
    "529": "Drilbur",
    "530": "Excadrill",
    "531": "Audino",
    "532": "Timburr",
    "533": "Gurdurr",
    "534": "Conkeldurr",
    "535": "Tympole",
    "536": "Palpitoad",
    "537": "Seismitoad",
    "538": "Throh",
    "539": "Sawk",
    "540": "Sewaddle",
    "541": "Swadloon",
    "542": "Leavanny",
    "543": "Venipede",
    "544": "Whirlipede",
    "545": "Scolipede",
    "546": "Cottonee",
    "547": "Whimsicott",
    "548": "Petilil",
    "549": "Lilligant",
    "550": "Basculin",
    "551": "Sandile",
    "552": "Krokorok",
    "553": "Krookodile",
    "554": "Darumaka",
    "555": "Darmanitan",
    "556": "Maractus",
    "557": "Dwebble",
    "558": "Crustle",
    "559": "Scraggy",
    "560": "Scrafty",
    "561": "Sigilyph",
    "562": "Yamask",
    "563": "Cofagrigus",
    "564": "Tirtouga",
    "565": "Carracosta",
    "566": "Archen",
    "567": "Archeops",
    "568": "Trubbish",
    "569": "Garbodor",
    "570": "Zorua",
    "571": "Zoroark",
    "572": "Minccino",
    "573": "Cinccino",
    "574": "Gothita",
    "575": "Gothorita",
    "576": "Gothitelle",
    "577": "Solosis",
    "578": "Duosion",
    "579": "Reuniclus",
    "580": "Ducklett",
    "581": "Swanna",
    "582": "Vanillite",
    "583": "Vanillish",
    "584": "Vanilluxe",
    "585": "Deerling",
    "586": "Sawsbuck",
    "587": "Emolga",
    "588": "Karrablast",
    "589": "Escavalier",
    "590": "Foongus",
    "591": "Amoonguss",
    "592": "Frillish",
    "593": "Jellicent",
    "594": "Alomomola",
    "595": "Joltik",
    "596": "Galvantula",
    "597": "Ferroseed",
    "598": "Ferrothorn",
    "599": "Klink",
    "600": "Klang",
    "601": "Klinklang",
    "602": "Tynamo",
    "603": "Eelektrik",
    "604": "Eelektross",
    "605": "Elgyem",
    "606": "Beheeyem",
    "607": "Litwick",
    "608": "Lampent",
    "609": "Chandelure",
    "610": "Axew",
    "611": "Fraxure",
    "612": "Haxorus",
    "613": "Cubchoo",
    "614": "Beartic",
    "615": "Cryogonal",
    "616": "Shelmet",
    "617": "Accelgor",
    "618": "Stunfisk",
    "619": "Mienfoo",
    "620": "Mienshao",
    "621": "Druddigon",
    "622": "Golett",
    "623": "Golurk",
    "624": "Pawniard",
    "625": "Bisharp",
    "626": "Bouffalant",
    "627": "Rufflet",
    "628": "Braviary",
    "629": "Vullaby",
    "630": "Mandibuzz",
    "631": "Heatmor",
    "632": "Durant",
    "633": "Deino",
    "634": "Zweilous",
    "635": "Hydreigon",
    "636": "Larvesta",
    "637": "Volcarona",
    "638": "Cobalion",
    "639": "Terrakion",
    "640": "Virizion",
    "641": "Tornadus",
    "642": "Thundurus",
    "643": "Reshiram",
    "644": "Zekrom",
    "645": "Landorus",
    "646": "Kyurem",
    "647": "Keldeo",
    "648": "Meloetta",
    "649": "Genesect",
    "650": "Chespin",
    "651": "Quilladin",
    "652": "Chesnaught",
    "653": "Fennekin",
    "654": "Braixen",
    "655": "Delphox",
    "656": "Froakie",
    "657": "Frogadier",
    "658": "Greninja",
    "659": "Bunnelby",
    "660": "Diggersby",
    "661": "Fletchling",
    "662": "Fletchinder",
    "663": "Talonflame",
    "664": "Scatterbug",
    "665": "Spewpa",
    "666": "Vivillon",
    "667": "Litleo",
    "668": "Pyroar",
    "669": "Flabébé",
    "670": "Floette",
    "671": "Florges",
    "672": "Skiddo",
    "673": "Gogoat",
    "674": "Pancham",
    "675": "Pangoro",
    "676": "Furfrou",
    "677": "Espurr",
    "678": "Meowstic",
    "679": "Honedge",
    "680": "Doublade",
    "681": "Aegislash",
    "682": "Spritzee",
    "683": "Aromatisse",
    "684": "Swirlix",
    "685": "Slurpuff",
    "686": "Inkay",
    "687": "Malamar",
    "688": "Binacle",
    "689": "Barbaracle",
    "690": "Skrelp",
    "691": "Dragalge",
    "692": "Clauncher",
    "693": "Clawitzer",
    "694": "Helioptile",
    "695": "Heliolisk",
    "696": "Tyrunt",
    "697": "Tyrantrum",
    "698": "Amaura",
    "699": "Aurorus",
    "700": "Sylveon",
    "701": "Hawlucha",
    "702": "Dedenne",
    "703": "Carbink",
    "704": "Goomy",
    "705": "Sliggoo",
    "706": "Goodra",
    "707": "Klefki",
    "708": "Phantump",
    "709": "Trevenant",
    "710": "Pumpkaboo",
    "711": "Gourgeist",
    "712": "Bergmite",
    "713": "Avalugg",
    "714": "Noibat",
    "715": "Noivern",
    "716": "Xerneas",
    "717": "Yveltal",
    "718": "Zygarde",
    "719": "Diancie",
    "720": "Hoopa",
    "721": "Volcanion",
    "722": "Rowlet",
    "723": "Dartrix",
    "724": "Decidueye",
    "725": "Litten",
    "726": "Torracat",
    "727": "Incineroar",
    "728": "Popplio",
    "729": "Brionne",
    "730": "Primarina",
    "731": "Pikipek",
    "732": "Trumbeak",
    "733": "Toucannon",
    "734": "Yungoos",
    "735": "Gumshoos",
    "736": "Grubbin",
    "737": "Charjabug",
    "738": "Vikavolt",
    "739": "Crabrawler",
    "740": "Crabominable",
    "741": "Oricorio",
    "742": "Cutiefly",
    "743": "Ribombee",
    "744": "Rockruff",
    "745": "Lycanroc",
    "746": "Wishiwashi",
    "747": "Mareanie",
    "748": "Toxapex",
    "749": "Mudbray",
    "750": "Mudsdale",
    "751": "Dewpider",
    "752": "Araquanid",
    "753": "Fomantis",
    "754": "Lurantis",
    "755": "Morelull",
    "756": "Shiinotic",
    "757": "Salandit",
    "758": "Salazzle",
    "759": "Stufful",
    "760": "Bewear",
    "761": "Bounsweet",
    "762": "Steenee",
    "763": "Tsareena",
    "764": "Comfey",
    "765": "Oranguru",
    "766": "Passimian",
    "767": "Wimpod",
    "768": "Golisopod",
    "769": "Sandygast",
    "770": "Palossand",
    "771": "Pyukumuku",
    "772": "Tipo Zero",
    "773": "Silvally",
    "774": "Minior",
    "775": "Komala",
    "776": "Turtonator",
    "777": "Togedemaru",
    "778": "Mimikyu",
    "779": "Bruxish",
    "780": "Drampa",
    "781": "Dhelmise",
    "782": "Jangmo-o",
    "783": "Hakamo-o",
    "784": "Kommo-o",
    "785": "Tapu Koko",
    "786": "Tapu Lele",
    "787": "Tapu Bulu",
    "788": "Tapu Fini",
    "789": "Cosmog",
    "790": "Cosmoem",
    "791": "Solgaleo",
    "792": "Lunala",
    "793": "Nihilego",
    "794": "Buzzwole",
    "795": "Pheromosa",
    "796": "Xurkitree",
    "797": "Celesteela",
    "798": "Kartana",
    "799": "Guzzlord",
    "800": "Necrozma",
    "801": "Magearna",
    "802": "Marshadow",
    "803": "Poipole",
    "804": "Naganadel",
    "805": "Stakataka",
    "806": "Blacephalon",
    "807": "Zeraora",
    "808": "Meltan",
    "809": "Melmetal",
    "810": "Grookey",
    "811": "Thwackey",
    "812": "Rillaboom",
    "813": "Scorbunny",
    "814": "Raboot",
    "815": "Cinderace",
    "816": "Sobble",
    "817": "Drizzile",
    "818": "Inteleon",
    "819": "Skwovet",
    "820": "Greedent",
    "821": "Rookidee",
    "822": "Corvisquire",
    "823": "Corviknight",
    "824": "Blipbug",
    "825": "Dottler",
    "826": "Orbeetle",
    "827": "Nickit",
    "828": "Thievul",
    "829": "Gossifleur",
    "830": "Eldegoss",
    "831": "Wooloo",
    "832": "Dubwool",
    "833": "Chewtle",
    "834": "Drednaw",
    "835": "Yamper",
    "836": "Boltund",
    "837": "Rolycoly",
    "838": "Carkol",
    "839": "Coalossal",
    "840": "Applin",
    "841": "Flapple",
    "842": "Appletun",
    "843": "Silicobra",
    "844": "Sandaconda",
    "845": "Cramorant",
    "846": "Arrokuda",
    "847": "Barraskewda",
    "848": "Toxel",
    "849": "Toxtricity",
    "850": "Sizzlipede",
    "851": "Centiskorch",
    "852": "Clobbopus",
    "853": "Grapploct",
    "854": "Sinistea",
    "855": "Polteageist",
    "856": "Hatenna",
    "857": "Hattrem",
    "858": "Hatterene",
    "859": "Impidimp",
    "860": "Morgrem",
    "861": "Grimmsnarl",
    "862": "Obstagoon",
    "863": "Perrserker",
    "864": "Cursola",
    "865": "Sirfetch’d",
    "866": "Mr. Rime",
    "867": "Runerigus",
    "868": "Milcery",
    "869": "Alcremie",
    "870": "Falinks",
    "871": "Pincurchin",
    "872": "Snom",
    "873": "Frosmoth",
    "874": "Stonjourner",
    "875": "Eiscue",
    "876": "Indeedee",
    "877": "Morpeko",
    "878": "Cufant",
    "879": "Copperajah",
    "880": "Dracozolt",
    "881": "Arctozolt",
    "882": "Dracovish",
    "883": "Arctovish",
    "884": "Duraludon",
    "885": "Dreepy",
    "886": "Drakloak",
    "887": "Dragapult",
    "888": "Zacian",
    "889": "Zamazenta",
    "890": "Eternatus",
    "891": "Kubfu",
    "892": "Urshifu",
    "893": "Zarude",
    "894": "Regieleki",
    "895": "Regidrago",
    "896": "Glastrier",
    "897": "Spectrier",
    "898": "Calyrex",
    "899": "Wyrdeer",
    "900": "Kleavor",
    "901": "Ursaluna",
    "902": "Basculegion",
    "903": "Sneasler",
    "904": "Overqwil",
    "905": "Enamorus",
    "906": "Sprigatito",
    "907": "Floragato",
    "908": "Meowscarada",
    "909": "Fuecoco",
    "910": "Crocalor",
    "911": "Skeledirge",
    "912": "Quaxly",
    "913": "Quaxwell",
    "914": "Quaquaval",
    "915": "Lechonk",
    "916": "Oinkologne",
    "917": "Tarountula",
    "918": "Spidops",
    "919": "Nymble",
    "920": "Lokix",
    "921": "Pawmi",
    "922": "Pawmo",
    "923": "Pawmot",
    "924": "Tandemaus",
    "925": "Maushold",
    "926": "Fidough",
    "927": "Dachsbun",
    "928": "Smoliv",
    "929": "Dolliv",
    "930": "Arboliva",
    "931": "Squawkabilly",
    "932": "Nacli",
    "933": "Naclstack",
    "934": "Garganacl",
    "935": "Charcadet",
    "936": "Armarouge",
    "937": "Ceruledge",
    "938": "Tadbulb",
    "939": "Bellibolt",
    "940": "Wattrel",
    "941": "Kilowattrel",
    "942": "Maschiff",
    "943": "Mabosstiff",
    "944": "Shroodle",
    "945": "Grafaiai",
    "946": "Bramblin",
    "947": "Brambleghast",
    "948": "Toedscool",
    "949": "Toedscruel",
    "950": "Klawf",
    "951": "Capsakid",
    "952": "Scovillain",
    "953": "Rellor",
    "954": "Rabsca",
    "955": "Flittle",
    "956": "Espathra",
    "957": "Tinkatink",
    "958": "Tinkatuff",
    "959": "Tinkaton",
    "960": "Wiglett",
    "961": "Wugtrio",
    "962": "Bombirdier",
    "963": "Finizen",
    "964": "Palafin",
    "965": "Varoom",
    "966": "Revavroom",
    "967": "Cyclizar",
    "968": "Orthworm",
    "969": "Glimmet",
    "970": "Glimmora",
    "971": "Greavard",
    "972": "Houndstone",
    "973": "Flamigo",
    "974": "Cetoddle",
    "975": "Cetitan",
    "976": "Veluza",
    "977": "Dondozo",
    "978": "Tatsugiri",
    "979": "Annihilape",
    "980": "Clodsire",
    "981": "Farigiraf",
    "982": "Dudunsparce",
    "983": "Kingambit",
    "984": "Grandizanne",
    "985": "Codaurlante",
    "986": "Fungofurioso",
    "987": "Crinealato",
    "988": "Alirasenti",
    "989": "Peldisabbia",
    "990": "Solcoferreo",
    "991": "Saccoferreo",
    "992": "Manoferrea",
    "993": "Colloferreo",
    "994": "Falenaferrea",
    "995": "Spineferree",
    "996": "Frigibax",
    "997": "Arctibax",
    "998": "Baxcalibur",
    "999": "Gimmighoul",
    "1000": "Gholdengo",
    "1001": "Wo-Chien",
    "1002": "Chien-Pao",
    "1003": "Ting-Lu",
    "1004": "Chi-Yu",
    "1005": "Lunaruggente",
    "1006": "Eroeferreo",
    "1007": "Koraidon",
    "1008": "Miraidon",
    "1009": "Acquecrespe",
    "1010": "Fogliaferrea",
    "1011": "Dipplin",
    "1012": "Poltchageist",
    "1013": "Sinistcha",
    "1014": "Okidogi",
    "1015": "Munkidori",
    "1016": "Fezandipiti",
    "1017": "Ogerpon",
}

var Nome_in_Numero = {
    "bulbasaur": "1",
    "ivysaur": "2",
    "venusaur": "3",
    "charmander": "4",
    "charmeleon": "5",
    "charizard": "6",
    "squirtle": "7",
    "wartortle": "8",
    "blastoise": "9",
    "caterpie": "10",
    "metapod": "11",
    "butterfree": "12",
    "weedle": "13",
    "kakuna": "14",
    "beedrill": "15",
    "pidgey": "16",
    "pidgeotto": "17",
    "pidgeot": "18",
    "rattata": "19",
    "raticate": "20",
    "spearow": "21",
    "fearow": "22",
    "ekans": "23",
    "arbok": "24",
    "pikachu": "25",
    "raichu": "26",
    "sandshrew": "27",
    "sandslash": "28",
    "nidoran♀": "29",
    "nidorina": "30",
    "nidoqueen": "31",
    "nidoran♂": "32",
    "nidorino": "33",
    "nidoking": "34",
    "clefairy": "35",
    "clefable": "36",
    "vulpix": "37",
    "ninetales": "38",
    "jigglypuff": "39",
    "wigglytuff": "40",
    "zubat": "41",
    "golbat": "42",
    "oddish": "43",
    "gloom": "44",
    "vileplume": "45",
    "paras": "46",
    "parasect": "47",
    "venonat": "48",
    "venomoth": "49",
    "diglett": "50",
    "dugtrio": "51",
    "meowth": "52",
    "persian": "53",
    "psyduck": "54",
    "golduck": "55",
    "mankey": "56",
    "primeape": "57",
    "growlithe": "58",
    "arcanine": "59",
    "poliwag": "60",
    "poliwhirl": "61",
    "poliwrath": "62",
    "abra": "63",
    "kadabra": "64",
    "alakazam": "65",
    "machop": "66",
    "machoke": "67",
    "machamp": "68",
    "bellsprout": "69",
    "weepinbell": "70",
    "victreebel": "71",
    "tentacool": "72",
    "tentacruel": "73",
    "geodude": "74",
    "graveler": "75",
    "golem": "76",
    "ponyta": "77",
    "rapidash": "78",
    "slowpoke": "79",
    "slowbro": "80",
    "magnemite": "81",
    "magneton": "82",
    "farfetch’d": "83",
    "doduo": "84",
    "dodrio": "85",
    "seel": "86",
    "dewgong": "87",
    "grimer": "88",
    "muk": "89",
    "shellder": "90",
    "cloyster": "91",
    "gastly": "92",
    "haunter": "93",
    "gengar": "94",
    "onix": "95",
    "drowzee": "96",
    "hypno": "97",
    "krabby": "98",
    "kingler": "99",
    "voltorb": "100",
    "electrode": "101",
    "exeggcute": "102",
    "exeggutor": "103",
    "cubone": "104",
    "marowak": "105",
    "hitmonlee": "106",
    "hitmonchan": "107",
    "lickitung": "108",
    "koffing": "109",
    "weezing": "110",
    "rhyhorn": "111",
    "rhydon": "112",
    "chansey": "113",
    "tangela": "114",
    "kangaskhan": "115",
    "horsea": "116",
    "seadra": "117",
    "goldeen": "118",
    "seaking": "119",
    "staryu": "120",
    "starmie": "121",
    "mr. mime": "122",
    "scyther": "123",
    "jynx": "124",
    "electabuzz": "125",
    "magmar": "126",
    "pinsir": "127",
    "tauros": "128",
    "magikarp": "129",
    "gyarados": "130",
    "lapras": "131",
    "ditto": "132",
    "eevee": "133",
    "vaporeon": "134",
    "jolteon": "135",
    "flareon": "136",
    "porygon": "137",
    "omanyte": "138",
    "omastar": "139",
    "kabuto": "140",
    "kabutops": "141",
    "aerodactyl": "142",
    "snorlax": "143",
    "articuno": "144",
    "zapdos": "145",
    "moltres": "146",
    "dratini": "147",
    "dragonair": "148",
    "dragonite": "149",
    "mewtwo": "150",
    "mew": "151",
    "chikorita": "152",
    "bayleef": "153",
    "meganium": "154",
    "cyndaquil": "155",
    "quilava": "156",
    "typhlosion": "157",
    "totodile": "158",
    "croconaw": "159",
    "feraligatr": "160",
    "sentret": "161",
    "furret": "162",
    "hoothoot": "163",
    "noctowl": "164",
    "ledyba": "165",
    "ledian": "166",
    "spinarak": "167",
    "ariados": "168",
    "crobat": "169",
    "chinchou": "170",
    "lanturn": "171",
    "pichu": "172",
    "cleffa": "173",
    "igglybuff": "174",
    "togepi": "175",
    "togetic": "176",
    "natu": "177",
    "xatu": "178",
    "mareep": "179",
    "flaaffy": "180",
    "ampharos": "181",
    "bellossom": "182",
    "marill": "183",
    "azumarill": "184",
    "sudowoodo": "185",
    "politoed": "186",
    "hoppip": "187",
    "skiploom": "188",
    "jumpluff": "189",
    "aipom": "190",
    "sunkern": "191",
    "sunflora": "192",
    "yanma": "193",
    "wooper": "194",
    "quagsire": "195",
    "espeon": "196",
    "umbreon": "197",
    "murkrow": "198",
    "slowking": "199",
    "misdreavus": "200",
    "unown": "201",
    "wobbuffet": "202",
    "girafarig": "203",
    "pineco": "204",
    "forretress": "205",
    "dunsparce": "206",
    "gligar": "207",
    "steelix": "208",
    "snubbull": "209",
    "granbull": "210",
    "qwilfish": "211",
    "scizor": "212",
    "shuckle": "213",
    "heracross": "214",
    "sneasel": "215",
    "teddiursa": "216",
    "ursaring": "217",
    "slugma": "218",
    "magcargo": "219",
    "swinub": "220",
    "piloswine": "221",
    "corsola": "222",
    "remoraid": "223",
    "octillery": "224",
    "delibird": "225",
    "mantine": "226",
    "skarmory": "227",
    "houndour": "228",
    "houndoom": "229",
    "kingdra": "230",
    "phanpy": "231",
    "donphan": "232",
    "porygon2": "233",
    "stantler": "234",
    "smeargle": "235",
    "tyrogue": "236",
    "hitmontop": "237",
    "smoochum": "238",
    "elekid": "239",
    "magby": "240",
    "miltank": "241",
    "blissey": "242",
    "raikou": "243",
    "entei": "244",
    "suicune": "245",
    "larvitar": "246",
    "pupitar": "247",
    "tyranitar": "248",
    "lugia": "249",
    "ho-oh": "250",
    "celebi": "251",
    "treecko": "252",
    "grovyle": "253",
    "sceptile": "254",
    "torchic": "255",
    "combusken": "256",
    "blaziken": "257",
    "mudkip": "258",
    "marshtomp": "259",
    "swampert": "260",
    "poochyena": "261",
    "mightyena": "262",
    "zigzagoon": "263",
    "linoone": "264",
    "wurmple": "265",
    "silcoon": "266",
    "beautifly": "267",
    "cascoon": "268",
    "dustox": "269",
    "lotad": "270",
    "lombre": "271",
    "ludicolo": "272",
    "seedot": "273",
    "nuzleaf": "274",
    "shiftry": "275",
    "taillow": "276",
    "swellow": "277",
    "wingull": "278",
    "pelipper": "279",
    "ralts": "280",
    "kirlia": "281",
    "gardevoir": "282",
    "surskit": "283",
    "masquerain": "284",
    "shroomish": "285",
    "breloom": "286",
    "slakoth": "287",
    "vigoroth": "288",
    "slaking": "289",
    "nincada": "290",
    "ninjask": "291",
    "shedinja": "292",
    "whismur": "293",
    "loudred": "294",
    "exploud": "295",
    "makuhita": "296",
    "hariyama": "297",
    "azurill": "298",
    "nosepass": "299",
    "skitty": "300",
    "delcatty": "301",
    "sableye": "302",
    "mawile": "303",
    "aron": "304",
    "lairon": "305",
    "aggron": "306",
    "meditite": "307",
    "medicham": "308",
    "electrike": "309",
    "manectric": "310",
    "plusle": "311",
    "minun": "312",
    "volbeat": "313",
    "illumise": "314",
    "roselia": "315",
    "gulpin": "316",
    "swalot": "317",
    "carvanha": "318",
    "sharpedo": "319",
    "wailmer": "320",
    "wailord": "321",
    "numel": "322",
    "camerupt": "323",
    "torkoal": "324",
    "spoink": "325",
    "grumpig": "326",
    "spinda": "327",
    "trapinch": "328",
    "vibrava": "329",
    "flygon": "330",
    "cacnea": "331",
    "cacturne": "332",
    "swablu": "333",
    "altaria": "334",
    "zangoose": "335",
    "seviper": "336",
    "lunatone": "337",
    "solrock": "338",
    "barboach": "339",
    "whiscash": "340",
    "corphish": "341",
    "crawdaunt": "342",
    "baltoy": "343",
    "claydol": "344",
    "lileep": "345",
    "cradily": "346",
    "anorith": "347",
    "armaldo": "348",
    "feebas": "349",
    "milotic": "350",
    "castform": "351",
    "kecleon": "352",
    "shuppet": "353",
    "banette": "354",
    "duskull": "355",
    "dusclops": "356",
    "tropius": "357",
    "chimecho": "358",
    "absol": "359",
    "wynaut": "360",
    "snorunt": "361",
    "glalie": "362",
    "spheal": "363",
    "sealeo": "364",
    "walrein": "365",
    "clamperl": "366",
    "huntail": "367",
    "gorebyss": "368",
    "relicanth": "369",
    "luvdisc": "370",
    "bagon": "371",
    "shelgon": "372",
    "salamence": "373",
    "beldum": "374",
    "metang": "375",
    "metagross": "376",
    "regirock": "377",
    "regice": "378",
    "registeel": "379",
    "latias": "380",
    "latios": "381",
    "kyogre": "382",
    "groudon": "383",
    "rayquaza": "384",
    "jirachi": "385",
    "deoxys": "386",
    "turtwig": "387",
    "grotle": "388",
    "torterra": "389",
    "chimchar": "390",
    "monferno": "391",
    "infernape": "392",
    "piplup": "393",
    "prinplup": "394",
    "empoleon": "395",
    "starly": "396",
    "staravia": "397",
    "staraptor": "398",
    "bidoof": "399",
    "bibarel": "400",
    "kricketot": "401",
    "kricketune": "402",
    "shinx": "403",
    "luxio": "404",
    "luxray": "405",
    "budew": "406",
    "roserade": "407",
    "cranidos": "408",
    "rampardos": "409",
    "shieldon": "410",
    "bastiodon": "411",
    "burmy": "412",
    "wormadam": "413",
    "mothim": "414",
    "combee": "415",
    "vespiquen": "416",
    "pachirisu": "417",
    "buizel": "418",
    "floatzel": "419",
    "cherubi": "420",
    "cherrim": "421",
    "shellos": "422",
    "gastrodon": "423",
    "ambipom": "424",
    "drifloon": "425",
    "drifblim": "426",
    "buneary": "427",
    "lopunny": "428",
    "mismagius": "429",
    "honchkrow": "430",
    "glameow": "431",
    "purugly": "432",
    "chingling": "433",
    "stunky": "434",
    "skuntank": "435",
    "bronzor": "436",
    "bronzong": "437",
    "bonsly": "438",
    "mime jr.": "439",
    "happiny": "440",
    "chatot": "441",
    "spiritomb": "442",
    "gible": "443",
    "gabite": "444",
    "garchomp": "445",
    "munchlax": "446",
    "riolu": "447",
    "lucario": "448",
    "hippopotas": "449",
    "hippowdon": "450",
    "skorupi": "451",
    "drapion": "452",
    "croagunk": "453",
    "toxicroak": "454",
    "carnivine": "455",
    "finneon": "456",
    "lumineon": "457",
    "mantyke": "458",
    "snover": "459",
    "abomasnow": "460",
    "weavile": "461",
    "magnezone": "462",
    "lickilicky": "463",
    "rhyperior": "464",
    "tangrowth": "465",
    "electivire": "466",
    "magmortar": "467",
    "togekiss": "468",
    "yanmega": "469",
    "leafeon": "470",
    "glaceon": "471",
    "gliscor": "472",
    "mamoswine": "473",
    "porygon-z": "474",
    "gallade": "475",
    "probopass": "476",
    "dusknoir": "477",
    "froslass": "478",
    "rotom": "479",
    "uxie": "480",
    "mesprit": "481",
    "azelf": "482",
    "dialga": "483",
    "palkia": "484",
    "heatran": "485",
    "regigigas": "486",
    "giratina": "487",
    "cresselia": "488",
    "phione": "489",
    "manaphy": "490",
    "darkrai": "491",
    "shaymin": "492",
    "arceus": "493",
    "victini": "494",
    "snivy": "495",
    "servine": "496",
    "serperior": "497",
    "tepig": "498",
    "pignite": "499",
    "emboar": "500",
    "oshawott": "501",
    "dewott": "502",
    "samurott": "503",
    "patrat": "504",
    "watchog": "505",
    "lillipup": "506",
    "herdier": "507",
    "stoutland": "508",
    "purrloin": "509",
    "liepard": "510",
    "pansage": "511",
    "simisage": "512",
    "pansear": "513",
    "simisear": "514",
    "panpour": "515",
    "simipour": "516",
    "munna": "517",
    "musharna": "518",
    "pidove": "519",
    "tranquill": "520",
    "unfezant": "521",
    "blitzle": "522",
    "zebstrika": "523",
    "roggenrola": "524",
    "boldore": "525",
    "gigalith": "526",
    "woobat": "527",
    "swoobat": "528",
    "drilbur": "529",
    "excadrill": "530",
    "audino": "531",
    "timburr": "532",
    "gurdurr": "533",
    "conkeldurr": "534",
    "tympole": "535",
    "palpitoad": "536",
    "seismitoad": "537",
    "throh": "538",
    "sawk": "539",
    "sewaddle": "540",
    "swadloon": "541",
    "leavanny": "542",
    "venipede": "543",
    "whirlipede": "544",
    "scolipede": "545",
    "cottonee": "546",
    "whimsicott": "547",
    "petilil": "548",
    "lilligant": "549",
    "basculin": "550",
    "sandile": "551",
    "krokorok": "552",
    "krookodile": "553",
    "darumaka": "554",
    "darmanitan": "555",
    "maractus": "556",
    "dwebble": "557",
    "crustle": "558",
    "scraggy": "559",
    "scrafty": "560",
    "sigilyph": "561",
    "yamask": "562",
    "cofagrigus": "563",
    "tirtouga": "564",
    "carracosta": "565",
    "archen": "566",
    "archeops": "567",
    "trubbish": "568",
    "garbodor": "569",
    "zorua": "570",
    "zoroark": "571",
    "minccino": "572",
    "cinccino": "573",
    "gothita": "574",
    "gothorita": "575",
    "gothitelle": "576",
    "solosis": "577",
    "duosion": "578",
    "reuniclus": "579",
    "ducklett": "580",
    "swanna": "581",
    "vanillite": "582",
    "vanillish": "583",
    "vanilluxe": "584",
    "deerling": "585",
    "sawsbuck": "586",
    "emolga": "587",
    "karrablast": "588",
    "escavalier": "589",
    "foongus": "590",
    "amoonguss": "591",
    "frillish": "592",
    "jellicent": "593",
    "alomomola": "594",
    "joltik": "595",
    "galvantula": "596",
    "ferroseed": "597",
    "ferrothorn": "598",
    "klink": "599",
    "klang": "600",
    "klinklang": "601",
    "tynamo": "602",
    "eelektrik": "603",
    "eelektross": "604",
    "elgyem": "605",
    "beheeyem": "606",
    "litwick": "607",
    "lampent": "608",
    "chandelure": "609",
    "axew": "610",
    "fraxure": "611",
    "haxorus": "612",
    "cubchoo": "613",
    "beartic": "614",
    "cryogonal": "615",
    "shelmet": "616",
    "accelgor": "617",
    "stunfisk": "618",
    "mienfoo": "619",
    "mienshao": "620",
    "druddigon": "621",
    "golett": "622",
    "golurk": "623",
    "pawniard": "624",
    "bisharp": "625",
    "bouffalant": "626",
    "rufflet": "627",
    "braviary": "628",
    "vullaby": "629",
    "mandibuzz": "630",
    "heatmor": "631",
    "durant": "632",
    "deino": "633",
    "zweilous": "634",
    "hydreigon": "635",
    "larvesta": "636",
    "volcarona": "637",
    "cobalion": "638",
    "terrakion": "639",
    "virizion": "640",
    "tornadus": "641",
    "thundurus": "642",
    "reshiram": "643",
    "zekrom": "644",
    "landorus": "645",
    "kyurem": "646",
    "keldeo": "647",
    "meloetta": "648",
    "genesect": "649",
    "chespin": "650",
    "quilladin": "651",
    "chesnaught": "652",
    "fennekin": "653",
    "braixen": "654",
    "delphox": "655",
    "froakie": "656",
    "frogadier": "657",
    "greninja": "658",
    "bunnelby": "659",
    "diggersby": "660",
    "fletchling": "661",
    "fletchinder": "662",
    "talonflame": "663",
    "scatterbug": "664",
    "spewpa": "665",
    "vivillon": "666",
    "litleo": "667",
    "pyroar": "668",
    "flabébé": "669",
    "floette": "670",
    "florges": "671",
    "skiddo": "672",
    "gogoat": "673",
    "pancham": "674",
    "pangoro": "675",
    "furfrou": "676",
    "espurr": "677",
    "meowstic": "678",
    "honedge": "679",
    "doublade": "680",
    "aegislash": "681",
    "spritzee": "682",
    "aromatisse": "683",
    "swirlix": "684",
    "slurpuff": "685",
    "inkay": "686",
    "malamar": "687",
    "binacle": "688",
    "barbaracle": "689",
    "skrelp": "690",
    "dragalge": "691",
    "clauncher": "692",
    "clawitzer": "693",
    "helioptile": "694",
    "heliolisk": "695",
    "tyrunt": "696",
    "tyrantrum": "697",
    "amaura": "698",
    "aurorus": "699",
    "sylveon": "700",
    "hawlucha": "701",
    "dedenne": "702",
    "carbink": "703",
    "goomy": "704",
    "sliggoo": "705",
    "goodra": "706",
    "klefki": "707",
    "phantump": "708",
    "trevenant": "709",
    "pumpkaboo": "710",
    "gourgeist": "711",
    "bergmite": "712",
    "avalugg": "713",
    "noibat": "714",
    "noivern": "715",
    "xerneas": "716",
    "yveltal": "717",
    "zygarde": "718",
    "diancie": "719",
    "hoopa": "720",
    "volcanion": "721",
    "rowlet": "722",
    "dartrix": "723",
    "decidueye": "724",
    "litten": "725",
    "torracat": "726",
    "incineroar": "727",
    "popplio": "728",
    "brionne": "729",
    "primarina": "730",
    "pikipek": "731",
    "trumbeak": "732",
    "toucannon": "733",
    "yungoos": "734",
    "gumshoos": "735",
    "grubbin": "736",
    "charjabug": "737",
    "vikavolt": "738",
    "crabrawler": "739",
    "crabominable": "740",
    "oricorio": "741",
    "cutiefly": "742",
    "ribombee": "743",
    "rockruff": "744",
    "lycanroc": "745",
    "wishiwashi": "746",
    "mareanie": "747",
    "toxapex": "748",
    "mudbray": "749",
    "mudsdale": "750",
    "dewpider": "751",
    "araquanid": "752",
    "fomantis": "753",
    "lurantis": "754",
    "morelull": "755",
    "shiinotic": "756",
    "salandit": "757",
    "salazzle": "758",
    "stufful": "759",
    "bewear": "760",
    "bounsweet": "761",
    "steenee": "762",
    "tsareena": "763",
    "comfey": "764",
    "oranguru": "765",
    "passimian": "766",
    "wimpod": "767",
    "golisopod": "768",
    "sandygast": "769",
    "palossand": "770",
    "pyukumuku": "771",
    "tipo zero": "772",
    "silvally": "773",
    "minior": "774",
    "komala": "775",
    "turtonator": "776",
    "togedemaru": "777",
    "mimikyu": "778",
    "bruxish": "779",
    "drampa": "780",
    "dhelmise": "781",
    "jangmo-o": "782",
    "hakamo-o": "783",
    "kommo-o": "784",
    "tapu koko": "785",
    "tapu lele": "786",
    "tapu bulu": "787",
    "tapu fini": "788",
    "cosmog": "789",
    "cosmoem": "790",
    "solgaleo": "791",
    "lunala": "792",
    "nihilego": "793",
    "buzzwole": "794",
    "pheromosa": "795",
    "xurkitree": "796",
    "celesteela": "797",
    "kartana": "798",
    "guzzlord": "799",
    "necrozma": "800",
    "magearna": "801",
    "marshadow": "802",
    "poipole": "803",
    "naganadel": "804",
    "stakataka": "805",
    "blacephalon": "806",
    "zeraora": "807",
    "meltan": "808",
    "melmetal": "809",
    "grookey": "810",
    "thwackey": "811",
    "rillaboom": "812",
    "scorbunny": "813",
    "raboot": "814",
    "cinderace": "815",
    "sobble": "816",
    "drizzile": "817",
    "inteleon": "818",
    "skwovet": "819",
    "greedent": "820",
    "rookidee": "821",
    "corvisquire": "822",
    "corviknight": "823",
    "blipbug": "824",
    "dottler": "825",
    "orbeetle": "826",
    "nickit": "827",
    "thievul": "828",
    "gossifleur": "829",
    "eldegoss": "830",
    "wooloo": "831",
    "dubwool": "832",
    "chewtle": "833",
    "drednaw": "834",
    "yamper": "835",
    "boltund": "836",
    "rolycoly": "837",
    "carkol": "838",
    "coalossal": "839",
    "applin": "840",
    "flapple": "841",
    "appletun": "842",
    "silicobra": "843",
    "sandaconda": "844",
    "cramorant": "845",
    "arrokuda": "846",
    "barraskewda": "847",
    "toxel": "848",
    "toxtricity": "849",
    "sizzlipede": "850",
    "centiskorch": "851",
    "clobbopus": "852",
    "grapploct": "853",
    "sinistea": "854",
    "polteageist": "855",
    "hatenna": "856",
    "hattrem": "857",
    "hatterene": "858",
    "impidimp": "859",
    "morgrem": "860",
    "grimmsnarl": "861",
    "obstagoon": "862",
    "perrserker": "863",
    "cursola": "864",
    "sirfetch’d": "865",
    "mr. rime": "866",
    "runerigus": "867",
    "milcery": "868",
    "alcremie": "869",
    "falinks": "870",
    "pincurchin": "871",
    "snom": "872",
    "frosmoth": "873",
    "stonjourner": "874",
    "eiscue": "875",
    "indeedee": "876",
    "morpeko": "877",
    "cufant": "878",
    "copperajah": "879",
    "dracozolt": "880",
    "arctozolt": "881",
    "dracovish": "882",
    "arctovish": "883",
    "duraludon": "884",
    "dreepy": "885",
    "drakloak": "886",
    "dragapult": "887",
    "zacian": "888",
    "zamazenta": "889",
    "eternatus": "890",
    "kubfu": "891",
    "urshifu": "892",
    "zarude": "893",
    "regieleki": "894",
    "regidrago": "895",
    "glastrier": "896",
    "spectrier": "897",
    "calyrex": "898",
    "wyrdeer": "899",
    "kleavor": "900",
    "ursaluna": "901",
    "basculegion": "902",
    "sneasler": "903",
    "overqwil": "904",
    "enamorus": "905",
    "sprigatito": "906",
    "floragato": "907",
    "meowscarada": "908",
    "fuecoco": "909",
    "crocalor": "910",
    "skeledirge": "911",
    "quaxly": "912",
    "quaxwell": "913",
    "quaquaval": "914",
    "lechonk": "915",
    "oinkologne": "916",
    "tarountula": "917",
    "spidops": "918",
    "nymble": "919",
    "lokix": "920",
    "pawmi": "921",
    "pawmo": "922",
    "pawmot": "923",
    "tandemaus": "924",
    "maushold": "925",
    "fidough": "926",
    "dachsbun": "927",
    "smoliv": "928",
    "dolliv": "929",
    "arboliva": "930",
    "squawkabilly": "931",
    "nacli": "932",
    "naclstack": "933",
    "garganacl": "934",
    "charcadet": "935",
    "armarouge": "936",
    "ceruledge": "937",
    "tadbulb": "938",
    "bellibolt": "939",
    "wattrel": "940",
    "kilowattrel": "941",
    "maschiff": "942",
    "mabosstiff": "943",
    "shroodle": "944",
    "grafaiai": "945",
    "bramblin": "946",
    "brambleghast": "947",
    "toedscool": "948",
    "toedscruel": "949",
    "klawf": "950",
    "capsakid": "951",
    "scovillain": "952",
    "rellor": "953",
    "rabsca": "954",
    "flittle": "955",
    "espathra": "956",
    "tinkatink": "957",
    "tinkatuff": "958",
    "tinkaton": "959",
    "wiglett": "960",
    "wugtrio": "961",
    "bombirdier": "962",
    "finizen": "963",
    "palafin": "964",
    "varoom": "965",
    "revavroom": "966",
    "cyclizar": "967",
    "orthworm": "968",
    "glimmet": "969",
    "glimmora": "970",
    "greavard": "971",
    "houndstone": "972",
    "flamigo": "973",
    "cetoddle": "974",
    "cetitan": "975",
    "veluza": "976",
    "dondozo": "977",
    "tatsugiri": "978",
    "annihilape": "979",
    "clodsire": "980",
    "farigiraf": "981",
    "dudunsparce": "982",
    "kingambit": "983",
    "grandizanne": "984",
    "codaurlante": "985",
    "fungofurioso": "986",
    "crinealato": "987",
    "alirasenti": "988",
    "peldisabbia": "989",
    "solcoferreo": "990",
    "saccoferreo": "991",
    "manoferrea": "992",
    "colloferreo": "993",
    "falenaferrea": "994",
    "spineferree": "995",
    "frigibax": "996",
    "arctibax": "997",
    "baxcalibur": "998",
    "gimmighoul": "999",
    "gholdengo": "1000",
    "wo-chien": "1001",
    "chien-pao": "1002",
    "ting-lu": "1003",
    "chi-yu": "1004",
    "lunaruggente": "1005",
    "eroeferreo": "1006",
    "koraidon": "1007",
    "miraidon": "1008",
    "acquecrespe": "1009",
    "fogliaferrea": "1010",
    "dipplin": "1011",
    "poltchageist": "1012",
    "sinistcha": "1013",
    "okidogi": "1014",
    "munkidori": "1015",
    "fezandipiti": "1016",
    "ogerpon": "1017",
};

var parole_ambigue = [
    "via vittoria",
    "torre lotta",
    "percorso 1",
    "percorso 2",
    "percorso 3",
    "percorso 4",
    "percorso 5",
    "percorso 6",
    "percorso 7",
    "percorso 8",
    "percorso 9",
    "percorso 10",
    "percorso 11",
    "percorso 12",
    "percorso 13",
    "percorso 14",
    "percorso 15",
    "percorso 16",
    "percorso 17",
    "percorso 18",
    "percorso 19",
    "percorso 20",
    "percorso 21",
    "percorso 22",
    "percorso 23",
    "percorso 24",
    "percorso 25",
    "percorso 26",
    "percorso 27",
    "percorso 28",
    "percorso 29",
    "percorso 30",
    "percorso 31",
    "percorso 32",
    "percorso 33",
    "percorso 34",
    "percorso 35",
    "percorso 36",
    "percorso 37",
    "percorso 38",
    "percorso 39",
    "percorso 40",
    "percorso 41",
    "percorso 42",
    "percorso 43",
    "percorso 44",
    "percorso 45",
    "percorso 46",
    "percorso 47",
    "percorso 48",
    "percorso 49",
    "percorso 50",
    "percorso 101",
    "percorso 102",
    "percorso 103",
    "percorso 104",
    "percorso 105",
    "percorso 106",
    "percorso 107",
    "percorso 108",
    "percorso 109",
    "percorso 110",
    "percorso 111",
    "percorso 112",
    "percorso 113",
    "percorso 114",
    "percorso 115",
    "percorso 116",
    "percorso 117",
    "percorso 118",
    "percorso 119",
    "percorso 120",
    "percorso 121",
    "percorso 122",
    "percorso 123",
    "percorso 124",
    "percorso 125",
    "percorso 126",
    "percorso 127",
    "percorso 128",
    "percorso 129",
    "percorso 130",
    "percorso 131",
    "percorso 132",
    "percorso 133",
    "percorso 134",
    "percorso 201",
    "percorso 202",
    "percorso 203",
    "percorso 204",
    "percorso 205",
    "percorso 206",
    "percorso 207",
    "percorso 208",
    "percorso 209",
    "percorso 210",
    "percorso 211",
    "percorso 212",
    "percorso 213",
    "percorso 214",
    "percorso 215",
    "percorso 216",
    "percorso 217",
    "percorso 218",
    "percorso 219",
    "percorso 220",
    "percorso 221",
    "percorso 222",
    "percorso 223",
    "percorso 224",
    "percorso 225",
    "percorso 226",
    "percorso 227",
    "percorso 228",
    "percorso 229",
    "percorso 230",
];

// traduzioniGrandiSotterranei / traduzioniGiochi / traduzioniSfondi / traduzioniRegioni / traduzioniClassiAllenatori